### ISSUE TITLE
Plex linking does not work

### ISSUE THREAD

**Issue by herki84** [ShokoAnime/ShokoServer#1060]
## VERSION INFORMATION

Server Version: 4.2.2.0

Desktop Version: 4.2.1.0

## LOG FILE

```[2023-04-23 15:53:13:427] Error|Dispatcher.CatchExceptionStatic => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://app.plex.tv/auth#?clientID=xxx' with working directory 'C:\Program Files (x86)\Shoko\Shoko Desktop'. Das System kann die angegebene Datei nicht finden.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Shoko.Desktop.Forms.LinkPlexForm.Hyperlink_RequestNavigate(Object sender, RequestNavigateEventArgs e) in C:\Users\Ricky\Documents\Github\ShokoDesktop\Shoko.Desktop\Forms\LinkPlexForm.xaml.cs:line 63
```

## DESCRIPTION

First problem is that the link in the desktop app doesn't open the default browser. Manually opening the link leads to a Plex authentication site, but after logging in no connection is made in Shoko. Also tested in WebUI 1.1.9, same issue, after logging in to Plex nothing else happens.

## STEPS TO REPRODUCE

Click "Link to Plex" in either desktop or WebUI, log in to Plex.

**Comment by ElementalCrisis** [comment]
Just tried, was able to link without issue. Running latest daily and beta Web UI.

@herki84 can you try again please.
