### ISSUE TITLE
v3/Series/Search Not Returning Results for Search Term: 86

### ISSUE THREAD

**Issue by natyusha** [ShokoAnime/ShokoServer#1105]
## VERSION INFORMATION

Server Version: Latest

Desktop Version: Latest

## LOG FILE
```
18:53:16| Kestrel --- Connection id "0HN1AGTFUUMCP", Request id "0HN1AGTFUUMCP:00000003": An unhandled exception was thrown by the application.: System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.Utilities.SeriesSearch.SearchSeries(SVR_JMMUser user, String query, Int32 limit, SearchFlags flags, Filter tagFilter) in /usr/src/app/source/Shoko.Server/Utilities/SeriesSearch.cs:line 238
   at Shoko.Server.API.v3.Controllers.SeriesController.SearchInternal(String query, Boolean fuzzy, Int32 limit) in /usr/src/app/source/Shoko.Server/API/v3/Controllers/SeriesController.cs:line 1867
   at lambda_method24901(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Shoko.Server.API.APIExtensions.<>c.<<UseAPI>b__4_0>d.MoveNext() in /usr/src/app/source/Shoko.Server/API/APIExtensions.cs:line 248
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   ```

## DESCRIPTION

Search for the text `86` using `/api/v3/Series/Search` and nothing happens

## STEPS TO REPRODUCE

Run: `/api/v3/Series/Search?query=86&fuzzy=false&limit=10`
Result: `Error: Internal Server Error`

**Comment by harshithmohan** [comment]
It was a one-character fix....
