### ISSUE TITLE
Error when trying to link White Album (2009) to tmdb

### ISSUE THREAD

**Issue by TheOne320** [ShokoAnime/ShokoServer#1191]
## VERSION INFORMATION

Server Version: 5.0.0.20 (e1abd9f)

Desktop Version: None, using WebUI.

## LOG FILE
[2024-10-23.log](https://github.com/user-attachments/files/17482824/2024-10-23.log)

```log
[2024-10-23 00:42:16:528] Error|Microsoft.AspNetCore.Server.Kestrel > Connection id "0HN7IN0OBR2GS", Request id "0HN7IN0OBR2GS:0000004D": An unhandled exception was thrown by the application.: System.ArgumentException: An item with the same key has already been added. Key: 34767
  at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
  at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer) at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdateCompanies(IEntityMetadata tmdbEntity, List`1 companies) 
  at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdateShow(Int32 showId, Boolean forceRefresh, Boolean downloadImages, Boolean downloadCrewAndCast, Boolean downloadAlternateOrdering, Boolean quickRefresh) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Providers\TMDB\TmdbMetadataService.cs:line 989
  at Shoko.Server.API.v3.Controllers.TmdbController.RefreshTmdbShowByShowID(Int32 showID, TmdbRefreshShowBody body) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Controllers\TmdbController.cs:line 1370
  at lambda_method9907(Closure, Object) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
  at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) 
  at Sentry.AspNetCore.SentryTracingMiddleware.InvokeAsync(HttpContext context) 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
  at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
  at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
  at Shoko.Server.API.APIExtensions.<>c.<<UseAPI>b__4_0>d.MoveNext() in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\APIExtensions.cs:line 235
```

## DESCRIPTION
The WebUI sees the entry for White Album on TMDB but when I click on the entry it bugs out.
![image](https://github.com/user-attachments/assets/d590d9f0-38bf-4048-a288-574617a71da7)
See also the errors in the log file.

## STEPS TO REPRODUCE
Just try to link White Album (2009) to TMDB.

**Comment by revam** [comment]
didn't meant to close it. mis tapped.
