### ISSUE TITLE
AVDump failed to install

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#1193]
## VERSION INFORMATION

Server Version: 5.0.0

Desktop Version: n/a

Web-UI: 2.1.2-dev.13

## LOG FILE

```2024-10-26 00:50:41
Info
Running AVDump session with id 1: "Z:\_new_Season_Autum_2024\Dandadan\[DKB] Dandadan - S01E04 [1080p][HEVC x265 10bit][Multi-Subs].mkv"
2024-10-26 00:50:41
Error
An error occurred while running AVDump session 1: Files: Z:\_new_Season_Autum_2024\Dandadan\[DKB] Dandadan - S01E04 [1080p][HEVC x265 10bit][Multi-Subs].mkv Stack Trace: at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at Shoko.Server.Utilities.AVDumpHelper.<>c__DisplayClass24_0.<DumpFiles>b__2() in D:\a\ShokoServer\ShokoServer\Shoko.Server\Utilities\AVDumpHelper.cs:line 212
2024-10-26 00:51:37
Trace
Scheduling DEFAULT.AVDumpFilesJob to run.
2024-10-26 00:51:38
Error
Unable to install AVDump3; "Cannot determine compressed stream type. Supported Reader Formats: Zip, GZip, BZip2, Tar, Rar, LZip, XZ": System.InvalidOperationException: Cannot determine compressed stream type. Supported Reader Formats: Zip, GZip, BZip2, Tar, Rar, LZip, XZ at SharpCompress.Readers.ReaderFactory.Open(Stream stream, ReaderOptions options) at Shoko.Server.Utilities.AVDumpHelper.PrepareAVDump(Boolean force) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Utilities\AVDumpHelper.cs:line 409
```

## DESCRIPTION

Very strange issue. AvDump all of a sudden failed to dump file. After retrying. the server deletes the files in "C:/Programdata/ShokoServer/AVDump" and tries to redownload avdump. That, also seems to fail, because the resulting "avdump.zip" is only several KB in size and its contents are:

```
<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="stylesheet" href="/assets/root-BWfhYFVx.css"/><link rel="icon" href="/favicon.ico"/><title>Shoko</title></head><body><div class="relative min-h-screen"><div class="absolute inset-0 h-[850px] bg-cover bg-center bg-no-repeat" style="background-image:linear-gradient(to bottom, 
      rgba(23, 24, 31, 0.85), 
      rgba(23, 24, 31, 0.88) 30%, 
      rgba(23, 24, 31, 0.93) 50%, 
      rgba(23, 24, 31, .96) 80%, 
      rgba(23, 24, 31, .99) 90%, 
      rgba(23, 24, 31, 1) 95%
      100%), 
      url(/images/banners/banner-9.jpg)"></div><header class="sticky top-0 z-20 w-full transition-all duration-300"><div class="mx-auto flex max-w-screen-2xl justify-between px-6 py-3 font-header"><div class="flex items-center gap-x-4 text-shoko-36"><img src="/images/common/shoko-icon.svg" alt="Shoko Site" class="size-16"/><a class="transition-colors" data-discover="true" href="/">Shoko</a></div><nav class="mx-8 flex flex-col items-center justify-center gap-6 font-header xl:flex-row hidden xl:flex"><a class="flex items-center gap-x-2 text-shoko-18 transition-colors" data-discover="true" href="/about">About</a><a class="flex items-center gap-x-2 text-shoko-18 transition-colors" data-discover="true" href="/blog">Blog</a><a href="https://docs.shokoanime.com/changelog/shoko-server" target="_blank" rel="noopener noreferrer" class="flex items-center gap-x-2 text-shoko-18 transition-colors"><span>Changelog</span></a><a class="flex items-center gap-x-2 text-shoko-18 transition-colors" data-discover="true" href="/contributors">Contributors</a><a class="flex items-center gap-x-2 text-shoko-18 transition-colors" data-discover="true" href="/downloads/">Downloads</a><a href="https://docs.shokoanime.com/" target="_blank" rel="noopener noreferrer" class="flex items-center gap-x-2 text-shoko-18 transition-colors"><span>Documentation</span></a><a href="https://github.com/ShokoAnime/" target="_blank" rel="noopener noreferrer" class="flex items-center gap-x-2 text-shoko-18 transition-colors"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><title>GitHub</title><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"></path></svg><span>GitHub</span></a><a href="https://discord.gg/vpeHDsg" target="_blank" rel="noopener noreferrer" class="flex items-center gap-x-2 text-shoko-18 transition-colors"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><title>Discord</title><path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z"></path></svg><span>Discord</span></a></nav><div class="flex items-center gap-x-2 xl:hidden"><button class="
  flex items-center justify-center
  font-body font-semibold
  transition-all duration-300 ease-in-out
  focus:outline-none focus:ring-2 focus:ring-shoko-link focus:ring-opacity-50
  disabled:opacity-50 disabled:cursor-not-allowed
 bg-shoko-bg border border-shoko-border text-shoko-text-header hover:text-shoko-link text-base px-4 py-3 gap-x-2 rounded-full" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-panel-left-close"><rect width="18" height="18" x="3" y="3" rx="2"></rect><path d="M9 3v18"></path><path d="m16 15-3-3 3-3"></path></svg></button></div></div></header><div class="relative mx-auto flex h-full min-h-[calc(100vh-221px)] max-w-screen-2xl flex-col px-6"><div class="my-auto flex h-full flex-col justify-center gap-y-8 text-center"><h2 class="text-[20vw] leading-none opacity-50">404</h2><div class="flex flex-col gap-y-4 text-shoko-24"><div class="">Something went wrong, and you broke the site.</div><div class="">Feel free to let <strong>EC</strong> know about it on<!-- --> <a class="text-shoko-link hover:text-shoko-link-hover" href="https://discord.com/">Discord</a>.</div></div></div><script>((STORAGE_KEY2, restoreKey) => {
    if (!window.history.state || !window.history.state.key) {
      let key2 = Math.random().toString(32).slice(2);
      window.history.replaceState({
        key: key2
      }, "");
    }
    try {
      let positions = JSON.parse(sessionStorage.getItem(STORAGE_KEY2) || "{}");
      let storedY = positions[restoreKey || window.history.state.key];
      if (typeof storedY === "number") {
        window.scrollTo(0, storedY);
      }
    } catch (error3) {
      console.error(error3);
      sessionStorage.removeItem(STORAGE_KEY2);
    }
  })("positions", null)</script><link rel="modulepreload" href="/assets/manifest-78452e7a.js"/><link rel="modulepreload" href="/assets/entry.client-CbT7dbIW.js"/><link rel="modulepreload" href="/assets/jsx-runtime-Lx8eRigg.js"/><link rel="modulepreload" href="/assets/components-BAkbOU8S.js"/><link rel="modulepreload" href="/assets/index-BKptdcxi.js"/><link rel="modulepreload" href="/assets/Button-C6oTZKc7.js"/><link rel="modulepreload" href="/assets/createLucideIcon-C3HroB3r.js"/><link rel="modulepreload" href="/assets/SiGithub-BIBxUIUk.js"/><link rel="modulepreload" href="/assets/useSetPageTitle-mJAJOdEK.js"/><link rel="modulepreload" href="/assets/useBackground-Bs4hpvrs.js"/><link rel="modulepreload" href="/assets/convertToProperName-BOtKB9in.js"/><link rel="modulepreload" href="/assets/root-Z9Hl8s9s.js"/><link rel="modulepreload" href="/assets/PageNotFound-DTZerMoy.js"/><link rel="modulepreload" href="/assets/404-CpDfi0d_.js"/><script>window.__remixContext = {"basename":"/","future":{"v3_fetcherPersist":true,"v3_relativeSplatPath":true,"v3_throwAbortReason":true,"v3_singleFetch":false,"v3_lazyRouteDiscovery":false,"unstable_optimizeDeps":false},"isSpaMode":false,"state":{"loaderData":{"404":null,"root":null},"actionData":null,"errors":null}};</script><script type="module" async="">import "/assets/manifest-78452e7a.js";
import * as route0 from "/assets/root-Z9Hl8s9s.js";
import * as route1 from "/assets/404-CpDfi0d_.js";

window.__remixRouteModules = {"root":route0,"404":route1};

import("/assets/entry.client-CbT7dbIW.js");</script></div><footer class="relative flex items-center justify-center bg-shoko-bg-alt p-6"><div class="flex flex-col gap-1 text-center"><div>© 2016-2024 Shoko. All rights reserved.</div><div>Images and related content are used for reference and non-commercial purposes.</div><div>All copyrights and trademarks are the property of their respective owners.</div></div></footer></div></body></html>
```

## STEPS TO REPRODUCE

1.) make avdump fail dumping a file
or delete avdump manually
2.) try to dump a file again
3.) Error will occur, "Error installing AVDump"

**Comment by t0815** [comment]
I just noticed, the resulting .zips content is a 404 from shoko itself.... where does shoko want to download avdump from?

**Comment by revam** [comment]
reinstall shoko server 5.0 (there were 5 release attempts for it), then delete the avdump folder and zip and let it reinstall it

**Comment by t0815** [comment]
still same error:

```
Unable to install AVDump3; "Cannot determine compressed stream type. Supported Reader Formats: Zip, GZip, BZip2, Tar, Rar, LZip, XZ": System.InvalidOperationException: Cannot determine compressed stream type. Supported Reader Formats: Zip, GZip, BZip2, Tar, Rar, LZip, XZ at SharpCompress.Readers.ReaderFactory.Open(Stream stream, ReaderOptions options) at Shoko.Server.Utilities.AVDumpHelper.PrepareAVDump(Boolean force) in D:\a\ShokoServer\ShokoServer\Shoko.Server\Utilities\AVDumpHelper.cs:line 409
```

**Comment by revam** [comment]
that error looks to me like the server wasn't properly reinstalled (e.g. for docker you would `docker pull ghcr.io/shokoanime/server:latest` followed by recreating the container using the cli or compose, etc.), or the zip file wasn't properly deleted before reattempting to let shoko install it.

**Comment by t0815** [comment]
im using windows installer. I did completely uninstall server, and deleted the AVDump folder and the avdump.zip in "Programdata/ShokoServer". What I didn't delete, where my settings and stuff in programdata. I even manually deleted shoko-server files in Programs, that where still in the folder.... hmmm
