### ISSUE TITLE
Error after importing file [ Quartz.JobExecutionException: could not insert: [Shoko.Server.Models.TMDB.TMDB_Person] ]

### ISSUE THREAD

**Issue by catchra** [ShokoAnime/ShokoServer#1194]
## VERSION INFORMATION

Server Version: 5.0.0.0
[(76da970)](https://github.com/ShokoAnime/ShokoServer/compare/76da970...master)

Desktop Version: N/A

## LOG FILE

```
15:43:52| TmdbMetadataService --- Released lock 'metadata' for Show 86034 after 00:00:53.5195196. (Reason: Update)
15:43:52| JobRunShell --- Job TMDB.UpdateTmdbShowJob_TmdbShowID:86034_DownloadImages:true threw a JobExecutionException: : Parameters: refire = False, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: could not insert: [Shoko.Server.Models.TMDB.TMDB_Person][SQL: INSERT INTO TMDB_Person (TmdbPersonID, EnglishName, EnglishBiography, Aliases, Gender, IsRestricted, BirthDay, DeathDay, PlaceOfBirth, CreatedAt, LastUpdatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
 ---> NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Server.Models.TMDB.TMDB_Person][SQL: INSERT INTO TMDB_Person (TmdbPersonID, EnglishName, EnglishBiography, Aliases, Gender, IsRestricted, BirthDay, DeathDay, PlaceOfBirth, CreatedAt, LastUpdatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
 ---> MySqlConnector.MySqlException (0x80004005): Incorrect string value: '\xF0\xA8\x9C\xAE||...' for column 'Aliases' at row 1
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 892
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(DbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSql, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSql, ISessionImplementor session, IBinder binder)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.InnerExecute(IExecutable executable)
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseDirectRepository`2.<>c__DisplayClass38_0.<Save>b__0() in /usr/src/app/source/Shoko.Server/Repositories/BaseDirectRepository.cs:line 155
   at Shoko.Server.Repositories.BaseRepository.Lock(Action action) in /usr/src/app/source/Shoko.Server/Repositories/BaseRepository.cs:line 17
   at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdatePerson(Int32 personId, Boolean forceRefresh, Boolean downloadImages) in /usr/src/app/source/Shoko.Server/Providers/TMDB/TmdbMetadataService.cs:line 1991
   at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdateShowSeasonsAndEpisodes(TvShow show, Boolean downloadCrewAndCast, Boolean forceRefresh, Boolean downloadImages, Boolean quickRefresh, Boolean shouldFireEvents) in /usr/src/app/source/Shoko.Server/Providers/TMDB/TmdbMetadataService.cs:line 1121
   at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdateShow(Int32 showId, Boolean forceRefresh, Boolean downloadImages, Boolean downloadCrewAndCast, Boolean downloadAlternateOrdering, Boolean quickRefresh) in /usr/src/app/source/Shoko.Server/Providers/TMDB/TmdbMetadataService.cs:line 929
   at Shoko.Server.Scheduling.Jobs.TMDB.UpdateTmdbShowJob.Process() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/TMDB/UpdateTmdbShowJob.cs:line 65
   at Shoko.Server.Scheduling.Jobs.BaseJob.Execute(IJobExecutionContext context) in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/BaseJob.cs:line 33
   --- End of inner exception stack trace ---
   at Shoko.Server.Scheduling.Jobs.BaseJob.Execute(IJobExecutionContext context) in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/BaseJob.cs:line 50
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken) [See nested exception: NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Server.Models.TMDB.TMDB_Person][SQL: INSERT INTO TMDB_Person (TmdbPersonID, EnglishName, EnglishBiography, Aliases, Gender, IsRestricted, BirthDay, DeathDay, PlaceOfBirth, CreatedAt, LastUpdatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
 ---> MySqlConnector.MySqlException (0x80004005): Incorrect string value: '\xF0\xA8\x9C\xAE||...' for column 'Aliases' at row 1
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 892
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(DbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSql, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSql, ISessionImplementor session, IBinder binder)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.InnerExecute(IExecutable executable)
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseDirectRepository`2.<>c__DisplayClass38_0.<Save>b__0() in /usr/src/app/source/Shoko.Server/Repositories/BaseDirectRepository.cs:line 155
   at Shoko.Server.Repositories.BaseRepository.Lock(Action action) in /usr/src/app/source/Shoko.Server/Repositories/BaseRepository.cs:line 17
   at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdatePerson(Int32 personId, Boolean forceRefresh, Boolean downloadImages) in /usr/src/app/source/Shoko.Server/Providers/TMDB/TmdbMetadataService.cs:line 1991
   at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdateShowSeasonsAndEpisodes(TvShow show, Boolean downloadCrewAndCast, Boolean forceRefresh, Boolean downloadImages, Boolean quickRefresh, Boolean shouldFireEvents) in /usr/src/app/source/Shoko.Server/Providers/TMDB/TmdbMetadataService.cs:line 1121
   at Shoko.Server.Providers.TMDB.TmdbMetadataService.UpdateShow(Int32 showId, Boolean forceRefresh, Boolean downloadImages, Boolean downloadCrewAndCast, Boolean downloadAlternateOrdering, Boolean quickRefresh) in /usr/src/app/source/Shoko.Server/Providers/TMDB/TmdbMetadataService.cs:line 929
   at Shoko.Server.Scheduling.Jobs.TMDB.UpdateTmdbShowJob.Process() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/TMDB/UpdateTmdbShowJob.cs:line 65
   at Shoko.Server.Scheduling.Jobs.BaseJob.Execute(IJobExecutionContext context) in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/BaseJob.cs:line 33]
15:43:52| Main --- Job Completed: Updating TMDB Show | Show: Arifureta: From Commonplace to World's Strongest, ShowID: 86034
15:43:52| Main --- Waiting: 0 | Blocked: 0 | Executing: 0/34 | Total: 0
15:44:05| UDPRateLimiter --- Time since last request is 59999 ms, not throttling
```

## DESCRIPTION

After shoko finished importing an episode this error was in the log

## STEPS TO REPRODUCE

I don't know if it can be reproduced as i did not see any other errors during the import process

**Comment by catchra** [comment]
sorry for the late reply

the DB engine is mysql version 8.0.37 running in a docker container
the DB container is configured to use br0 as its network with a hardcoded ip address
shoko server is also running as a container with its network set to bridge

if you need any specific info from the database, give me the query to run i will post the results asap

**Comment by da3dsoul** [comment]
That's fine. The database type and version is all we need to determine that issue, I think

**Comment by krbrs** [comment]
@catchra Can you please check if this is fixed for you with the latest daily of the Server?
A few changes were made e.g. with this commit https://github.com/ShokoAnime/ShokoServer/commit/77600393dd611958691d6a2f88b1aa2a2334dca5 which should set the collation correctly for the failed tables in MySQL.

I'll close the issue - if it's not fixed, please reopen.
