### ISSUE TITLE
"Failed AniDB Login and Connection" from Shoko, but container itself is able to log in

### ISSUE THREAD

**Issue by tgxiii** [ShokoAnime/ShokoServer#1195]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 5.0.0

Desktop Version: n/a

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

[2024-10-29.log](https://github.com/user-attachments/files/17553011/2024-10-29.log)

## DESCRIPTION

Shoko has stopped processing tasks in the queue. It seems to be an issue with connecting to AniDB.

The installation is Docker on a MacOS host. On the host itself, I was able to load the AniDB website and log in with the same credentials I  have saved in Shoko.

## STEPS TO REPRODUCE

1. Fresh install of Shoko on Docker using ~MacOS Sonoma~ Windows 10 as host
2. Add import folders and run import

Expected:
All jobs finish

Actual:
Most tasks ran, but stopped with 191 tasks still left. The WebUI shows `Get Cross-References for File` tasks.

**Comment by tgxiii** [comment]
I installed netcat in the Docker container to check if it can at least connect to the UDP API and it looks like it can:

![image](https://github.com/user-attachments/assets/bf67fbf9-4674-45c5-b9ad-92ec5d7319d6)

**Comment by revam** [comment]
@tgxiii what does the log say when it fails to connect? And can you send a few lines above when it errs out for context of what the server was doing too?

Preferably the docker container output if you haven't enabled trace logging for the log file (since the docker container output will always be trace level).

**Comment by tgxiii** [comment]
New log file with trace logs enabled:

[2024-10-31.log](https://github.com/user-attachments/files/17595999/2024-10-31.log)

Relevant snippet:

```
[2024-10-31 21:10:50:286] Info|Shoko.Server.Server.ShokoServer > Initializing Session Factory...
[2024-10-31 21:10:50:286] Trace|Shoko.Server.Server.ServerState > Starting Server: Initializing Session Factory...
[2024-10-31 21:10:50:286] Trace|Shoko.Server.Server.ServerState > Starting Server: Initializing File Watchers...
[2024-10-31 21:10:50:298] Info|Shoko.Server.Services.FileWatcherService > Watching ImportFolder: Anime || /data/anime/
[2024-10-31 21:10:50:306] Info|Shoko.Server.Services.FileWatcherService > Parsed ImportFolderLocation: /data/anime/
[2024-10-31 21:10:53:236] Info|Shoko.Server.Server.ShokoServer > Starting Server: Complete!
[2024-10-31 21:10:53:236] Trace|Shoko.Server.Server.ServerState > Starting Server: Complete!
[2024-10-31 21:10:53:349] Trace|Main > Job Started: Getting Cross-References for File | File Path: Gekijouban Kara no Kyoukai։ The Garden of Sinners/[Coalgirls] The Garden of Sinners  [AE5E739C]_194101.mkv
[2024-10-31 21:10:53:349] Trace|Main > Waiting: 0 | Blocked: 8 | Executing: 1/6 | Total: 9
[2024-10-31 21:10:53:353] Info|ProcessFileJob_VideoLocalID:12554_ForceAniDB:true > Processing ProcessFileJob: Gekijouban Kara no Kyoukai։ The Garden of Sinners/[Coalgirls] The Garden of Sinners  [AE5E739C]_194101.mkv
[2024-10-31 21:10:53:353] Trace|ProcessFileJob_VideoLocalID:12554_ForceAniDB:true > Checking for AniDB_File record for: 0135DB942BCC0663C6248E191CF3DB40 --- Gekijouban Kara no Kyoukai։ The Garden of Sinners/[Coalgirls] The Garden of Sinners  [AE5E739C]_194101.mkv
[2024-10-31 21:10:53:366] Debug|ProcessFileJob_VideoLocalID:12554_ForceAniDB:true > Getting AniDB_File record from AniDB....
[2024-10-31 21:10:53:377] Info|GetAniDBFileJob_VideoLocalID:12554_ForceAniDB:true > Get AniDB file info: 12554
[2024-10-31 21:10:53:390] Trace|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > Logging in
[2024-10-31 21:10:53:411] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Time since last request is 51577 ms, not throttling
[2024-10-31 21:10:53:411] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Sending AniDB command
[2024-10-31 21:10:53:423] Trace|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > AniDB UDP Call: (Using ASCII) AUTH user=tgxiii&pass=****&protover=3&client=ommserver&clientver=2&comp=1&imgserver=1&enc=utf-16
[2024-10-31 21:11:23:488] Warn|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > AniDB request timed out. Checking Network and trying again
[2024-10-31 21:11:23:488] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Checking LAN Connectivity…
[2024-10-31 21:11:23:488] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Found a local gateway to use
[2024-10-31 21:11:23:488] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Checking WAN Connectivity…
[2024-10-31 21:11:23:488] Trace|Shoko.Server.Services.Connectivity.CloudFlareConnectivityMonitor > Trying to connect to CloudFlare
[2024-10-31 21:11:23:488] Trace|Shoko.Server.Services.Connectivity.MicrosoftConnectivityMonitor > Trying to connect to Microsoft
[2024-10-31 21:11:23:488] Trace|Shoko.Server.Services.Connectivity.MozillaConnectivityMonitor > Trying to connect to Mozilla
[2024-10-31 21:11:23:488] Trace|Shoko.Server.Services.Connectivity.WeChatConnectivityMonitor > Trying to connect to WeChat
[2024-10-31 21:11:23:548] Trace|Shoko.Server.Services.Connectivity.MozillaConnectivityMonitor > Successfully connected to Mozilla in 52ms
[2024-10-31 21:11:23:567] Trace|Shoko.Server.Services.Connectivity.MicrosoftConnectivityMonitor > Successfully connected to Microsoft in 73ms
[2024-10-31 21:11:23:633] Trace|Shoko.Server.Services.Connectivity.CloudFlareConnectivityMonitor > Successfully connected to CloudFlare in 139ms
[2024-10-31 21:11:24:537] Trace|Shoko.Server.Services.Connectivity.WeChatConnectivityMonitor > Successfully connected to WeChat in 1041ms
[2024-10-31 21:11:24:539] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Successfully connected to 4/4 internet service endpoints
[2024-10-31 21:11:24:539] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Time since last request is 31039 ms, not throttling
[2024-10-31 21:11:24:539] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Sending AniDB command
[2024-10-31 21:11:24:539] Trace|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > AniDB UDP Call: (Using ASCII) AUTH user=tgxiii&pass=****&protover=3&client=ommserver&clientver=2&comp=1&imgserver=1&enc=utf-16
[2024-10-31 21:11:54:620] Error|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > Failed to send AniDB message: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.SocketReceiveFromResult>.GetResult(Int16 token)
   at Shoko.Server.Providers.AniDB.UDP.AniDBSocketHandler.SendUnsafe(Byte[] payload, Byte[] result) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBSocketHandler.cs:line 67
   at Shoko.Server.Providers.AniDB.UDP.AniDBSocketHandler.Send(Byte[] payload) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBSocketHandler.cs:line 48
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.<>c__DisplayClass53_0.<<SendInternal>b__3>d.MoveNext() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 294
--- End of stack trace from previous location ---
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.<>c__DisplayClass53_0.<<SendInternal>b__2>d.MoveNext() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 283
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAndCaptureAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
[2024-10-31 21:11:54:755] Error|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > Unable to login to AniDB: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Shoko.Server.Providers.AniDB.UDP.Connection.RequestLogin.Send() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/Connection/RequestLogin.cs:line 53
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.LoginWithFallbacks(String username, String password) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 488
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.LoginWithFallbacks(String username, String password)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login(String username, String password) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 451
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login(String username, String password)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 419
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login()
   at Shoko.Server.Providers.AniDB.UDP.Generic.UDPRequest`1.Send() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/Generic/UDPRequest.cs:line 37
   at Shoko.Server.Scheduling.Jobs.AniDB.GetAniDBFileJob.Process() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/AniDB/GetAniDBFileJob.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.AniDB.GetAniDBFileJob.Process()
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.TryGetAniDBFileFromAniDB(Dictionary`2 animeIDs) in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/Shoko/ProcessFileJob.cs:line 342
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.TryGetAniDBFileFromAniDB(Dictionary`2 animeIDs)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.ProcessFile_AniDB() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/Shoko/ProcessFileJob.cs:line 122
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.ProcessFile_AniDB()
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.Process() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/Shoko/ProcessFileJob.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.Process()
   at Shoko.Server.Scheduling.Jobs.BaseJob.Execute(IJobExecutionContext context) in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/BaseJob.cs:line 33
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.BaseJob.Execute(IJobExecutionContext context)
   at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.ScopedJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   at Quartz.Core.QuartzSchedulerThread.<>c__DisplayClass26_0.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---

[2024-10-31 21:11:54:784] Trace|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > Failed to login to AniDB. Issuing a Logout command and retrying
[2024-10-31 21:11:54:784] Trace|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > Logging in
[2024-10-31 21:11:54:784] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Time since last request is 30178 ms, not throttling
[2024-10-31 21:11:54:784] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Sending AniDB command
[2024-10-31 21:11:54:784] Trace|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > AniDB UDP Call: (Using ASCII) AUTH user=tgxiii&pass=****&protover=3&client=ommserver&clientver=2&comp=1&imgserver=1&enc=utf-16
[2024-10-31 21:12:24:835] Warn|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > AniDB request timed out. Checking Network and trying again
[2024-10-31 21:12:24:835] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Checking LAN Connectivity…
[2024-10-31 21:12:24:835] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Found a local gateway to use
[2024-10-31 21:12:24:835] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Checking WAN Connectivity…
[2024-10-31 21:12:24:835] Trace|Shoko.Server.Services.Connectivity.MicrosoftConnectivityMonitor > Trying to connect to Microsoft
[2024-10-31 21:12:24:835] Trace|Shoko.Server.Services.Connectivity.CloudFlareConnectivityMonitor > Trying to connect to CloudFlare
[2024-10-31 21:12:24:835] Trace|Shoko.Server.Services.Connectivity.MozillaConnectivityMonitor > Trying to connect to Mozilla
[2024-10-31 21:12:24:835] Trace|Shoko.Server.Services.Connectivity.WeChatConnectivityMonitor > Trying to connect to WeChat
[2024-10-31 21:12:24:854] Trace|Shoko.Server.Services.Connectivity.MozillaConnectivityMonitor > Successfully connected to Mozilla in 8ms
[2024-10-31 21:12:24:854] Trace|Shoko.Server.Services.Connectivity.MicrosoftConnectivityMonitor > Successfully connected to Microsoft in 15ms
[2024-10-31 21:12:24:904] Trace|Shoko.Server.Services.Connectivity.CloudFlareConnectivityMonitor > Successfully connected to CloudFlare in 60ms
[2024-10-31 21:12:26:233] Trace|Shoko.Server.Services.Connectivity.WeChatConnectivityMonitor > Successfully connected to WeChat in 1385ms
[2024-10-31 21:12:26:234] Info|Shoko.Server.Services.Connectivity.ConnectivityService > Successfully connected to 4/4 internet service endpoints
[2024-10-31 21:12:26:234] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Time since last request is 31391 ms, not throttling
[2024-10-31 21:12:26:234] Trace|Shoko.Server.Providers.AniDB.UDP.UDPRateLimiter > Sending AniDB command
[2024-10-31 21:12:26:234] Trace|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > AniDB UDP Call: (Using ASCII) AUTH user=tgxiii&pass=****&protover=3&client=ommserver&clientver=2&comp=1&imgserver=1&enc=utf-16
[2024-10-31 21:12:56:289] Error|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > Failed to send AniDB message: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.SocketReceiveFromResult>.GetResult(Int16 token)
   at Shoko.Server.Providers.AniDB.UDP.AniDBSocketHandler.SendUnsafe(Byte[] payload, Byte[] result) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBSocketHandler.cs:line 67
   at Shoko.Server.Providers.AniDB.UDP.AniDBSocketHandler.Send(Byte[] payload) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBSocketHandler.cs:line 48
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.<>c__DisplayClass53_0.<<SendInternal>b__3>d.MoveNext() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 294
--- End of stack trace from previous location ---
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.<>c__DisplayClass53_0.<<SendInternal>b__2>d.MoveNext() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 283
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAndCaptureAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
[2024-10-31 21:12:56:306] Error|Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler > Unable to login to AniDB: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Shoko.Server.Providers.AniDB.UDP.Connection.RequestLogin.Send() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/Connection/RequestLogin.cs:line 53
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.LoginWithFallbacks(String username, String password) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 488
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.LoginWithFallbacks(String username, String password)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login(String username, String password) in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 451
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login(String username, String password)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/AniDBUDPConnectionHandler.cs:line 426
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Providers.AniDB.UDP.AniDBUDPConnectionHandler.Login()
   at Shoko.Server.Providers.AniDB.UDP.Generic.UDPRequest`1.Send() in /usr/src/app/source/Shoko.Server/Providers/AniDB/UDP/Generic/UDPRequest.cs:line 37
   at Shoko.Server.Scheduling.Jobs.AniDB.GetAniDBFileJob.Process() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/AniDB/GetAniDBFileJob.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.AniDB.GetAniDBFileJob.Process()
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.TryGetAniDBFileFromAniDB(Dictionary`2 animeIDs) in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/Shoko/ProcessFileJob.cs:line 342
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.TryGetAniDBFileFromAniDB(Dictionary`2 animeIDs)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.ProcessFile_AniDB() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/Shoko/ProcessFileJob.cs:line 122
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.ProcessFile_AniDB()
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.Process() in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/Shoko/ProcessFileJob.cs:line 82
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.Shoko.ProcessFileJob.Process()
   at Shoko.Server.Scheduling.Jobs.BaseJob.Execute(IJobExecutionContext context) in /usr/src/app/source/Shoko.Server/Scheduling/Jobs/BaseJob.cs:line 33
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Shoko.Server.Scheduling.Jobs.BaseJob.Execute(IJobExecutionContext context)
   at Quartz.Simpl.MicrosoftDependencyInjectionJobFactory.ScopedJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   at Quartz.Core.QuartzSchedulerThread.<>c__DisplayClass26_0.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
```

**Comment by revam** [comment]
@da3dsoul any idea why it is timing out inside shoko but otherwise works fine in the container?

**Comment by revam** [comment]
@da3dsoul you got some free time to give your thoughts if any?

**Comment by revam** [comment]
@tgxiii try exposing UDP traffic on port 4556 from the container.
E.g. add `-p 4556:4556/udp` to the CLI command, or do the equivalent for the compose file or in the TrueNAS UI.

**Comment by tgxiii** [comment]
Tried it. Issue persists.

**Comment by revam** [comment]
@da3dsoul, do you think the changes you did today/yesterday on daily with the anidb handler will help in this case?

@tgxiii, can you try running the latest `daily` tag to see if it is any different?

**Comment by da3dsoul** [comment]
It's possible

**Comment by da3dsoul** [comment]
Though that log is a timeout

**Comment by tgxiii** [comment]
I tried using `daily` but I was still getting the issue.

I moved to a different host, and it's working there.
