### ISSUE TITLE
Restarting Server While Running Produces Error

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoServer#435]
Getting the following error when restarting Server while it's running which has been possible for as long as I've been using JMM Server.

`[2016-09-24 03:53:26:111] Error|BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork => DatabaseExtensions.InitDB Could not init database: System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMServer.Repositories.Cached.GroupFilterRepository.PostProcess() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\Cached\GroupFilterRepository.cs:line 87
   at JMMServer.Repositories.RepoFactory.Init() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Repositories\RepoFactory.cs:line 127
   at JMMServer.Databases.DatabaseExtensions.InitDB(IDatabase database) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Databases\DatabaseExtensions.cs:line 83`

Have to completely close JMM Server as I get the following error after

`[2016-09-24 03:58:03:260] Error|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => MainWindow.workerSetupDB_DoWork System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at JMMServer.AniDBHelper.CloseConnections() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\AniDBHelper.cs:line 204
   at JMMServer.AniDBHelper.Dispose() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\AniDBHelper.cs:line 196
   at JMMServer.MainWindow.AniDBDispose() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\MainWindow.xaml.cs:line 2756
   at JMMServer.MainWindow.workerSetupDB_DoWork(Object sender, DoWorkEventArgs e) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\MainWindow.xaml.cs:line 1097`

Running latest master.

**Comment by maxpiva** [comment]
The first bug was squashed i think i latest master. moving this (        PostProcessFilters = new List<GroupFilter>(); ) to the constructor, the second one is normal, we should hide or have better handling of the closeconnection. It can be considered as no bug, or reported as an error, but not trapped.

**Comment by Jimmyson** [comment]
The second error, whist like what @maxpiva says, is just an notice exception, which is thrown when the Socket connection is already disconnected.
I have a way to check for active connections to prevent this exception to happen safely.
I just need to push. Will do if ok!
