### ISSUE TITLE
"Download watched state from MAL" is not working. 

### ISSUE THREAD

**Issue by Kezxo** [ShokoAnime/ShokoServer#527]
I have been having some issues downloading watched states from MAL. This is from todays log:

First time I tried to press the button in the desktop client:
```
[2016-12-11 20:43:50:286] Error|JMMServiceImplementation.IsWebCacheAdmin => AzureWebAPI.Admin_AuthUser => AzureWebAPI.SendData Error(1) in XMLServiceQueue.SendData: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.Azure.AzureWebAPI.SendData(String uri, String json, String verb) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\Azure\AzureWebAPI.cs:line 514
```
Then I restarted the server and cleared all queued commands and tried again:
```
[2016-12-11 21:01:11:635] Error|CommandRequest_MALUpdatedWatchedStatus.ProcessCommand => MALHelper.UpdateMALSeries => MALHelper.AddAnime System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.MyAnimeList.MALHelper.SendMALAuthenticatedRequest(String url) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 132
   at JMMServer.Providers.MyAnimeList.MALHelper.AddAnime(Int32 animeId, Int32 lastEpisodeWatched, Int32 status, Int32 score, Int32 downloadedEps, String fanSubs) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 583
[2016-12-11 21:01:12:288] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_MALUpdatedWatchedStatus.ProcessCommand Processing CommandRequest_MALUpdatedWatchedStatus: 202
[2016-12-11 21:01:14:170] Error|CommandRequest_MALUpdatedWatchedStatus.ProcessCommand => MALHelper.UpdateMALSeries => MALHelper.AddAnime System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.MyAnimeList.MALHelper.SendMALAuthenticatedRequest(String url) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 132
   at JMMServer.Providers.MyAnimeList.MALHelper.AddAnime(Int32 animeId, Int32 lastEpisodeWatched, Int32 status, Int32 score, Int32 downloadedEps, String fanSubs) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 583
```
More logs if you need it:
[2016-12-11.zip](https://github.com/japanesemediamanager/ShokoServer/files/644788/2016-12-11.zip)

**Comment by hidden4003** [comment]
What version are you using? Please try the latest release your issue might've been fixed there, judging by the logs it is looking like some intermittent issue either with MAL or the network.

**Comment by Kezxo** [comment]
I updated today and I still get some MAL errors, however they do seem a bit different.

I get this one again and again
```
[2017-01-28 14:03:38:769] Error|CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_MALSearchAnime.ProcessCommand => MALHelper.SearchAnimesByTitle System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.MyAnimeList.MALHelper.SendMALAuthenticatedRequest(String url) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 134
   at JMMServer.Providers.MyAnimeList.MALHelper.SearchAnimesByTitle(String searchTitle) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 40
```

Here is a different less frequent one combined with the one above: 
```
[2017-01-29 01:47:17:442] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_MALUpdatedWatchedStatus.ProcessCommand Processing CommandRequest_MALUpdatedWatchedStatus: 11985
[2017-01-29 01:47:17:464] Error|CommandRequest_MALUpdatedWatchedStatus.ProcessCommand => MALHelper.UpdateMALSeries => MALHelper.GetMALAnimeList System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.MyAnimeList.MALHelper.SendMALAuthenticatedRequest(String url) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 134
   at JMMServer.Providers.MyAnimeList.MALHelper.GetMALAnimeList() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 346
[2017-01-29 01:47:18:482] Error|CommandRequest_MALUpdatedWatchedStatus.ProcessCommand => MALHelper.UpdateMALSeries => MALHelper.AddAnime System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.MyAnimeList.MALHelper.SendMALAuthenticatedRequest(String url) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 134
   at JMMServer.Providers.MyAnimeList.MALHelper.AddAnime(Int32 animeId, Int32 lastEpisodeWatched, Int32 status, Int32 score, Int32 downloadedEps, String fanSubs) in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Providers\MyAnimeList\MALHelper.cs:line 583
[2017-01-29 01:47:18:489] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_MALUpdatedWatchedStatus.ProcessCommand Processing CommandRequest_MALUpdatedWatchedStatus: 12374
```
Looks like something worked at the end? 
Logs:
[2017-01-29.zip](https://github.com/japanesemediamanager/ShokoServer/files/737233/2017-01-29.zip)

**Comment by da3dsoul** [comment]
Closing this as we are dropping MAL Support
