### ISSUE TITLE
Move files from Watched folder to Drop Destination broke after upgrade to 3.8.0.0

### ISSUE THREAD

**Issue by Animeimp** [ShokoAnime/ShokoServer#655]
```
[2017-08-12 07:36:52:569] Error|List`1.ForEach => SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.MoveFileIfRequired Could not MOVE file: Z:\Anime\unprocessed\[HorribleSubs]_Hell_Girl-_Fourth_Twilight_-_5_(1280x720_H264)_[540277AE].mkv -- System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalDirectory' to type 'NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalDrive'.
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFileSystem.<QuotaAsync>d__6.MoveNext() in D:\My Files\Documents\GitHub\ShokoServer\CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFileSystem.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass1_0.<<Quota>b__0>d.MoveNext() in D:\My Files\Documents\GitHub\ShokoServer\CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 19
--- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NutzCode.CloudFileSystem.SyncExtensions.Quota(IFileSystem filesys) in D:\My Files\Documents\GitHub\ShokoServer\CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 19
   at Shoko.Server.Renamer.LegacyRenamer.GetDestinationFolder(SVR_VideoLocal_Place video) in D:\My Files\Documents\GitHub\ShokoServer\Shoko.Server\Renamer\LegacyRenamer.cs:line 2053
   at Shoko.Server.Models.SVR_VideoLocal_Place.MoveFileIfRequired() in D:\My Files\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 777
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalDirectory' to type 'NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalDrive'.
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFileSystem.<QuotaAsync>d__6.MoveNext() in D:\My Files\Documents\GitHub\ShokoServer\CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFileSystem.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NutzCode.CloudFileSystem.SyncExtensions.<>c__DisplayClass1_0.<<Quota>b__0>d.MoveNext() in D:\My Files\Documents\GitHub\ShokoServer\CloudFileSystem\NutzCode.CloudFileSystem\SyncExtensions.cs:line 19<---
```

Rename code
```
DO ADD '[%grp] '
IF I(eng) DO ADD '%eng '
IF I(ann);I(!eng) DO ADD '%ann '
IF T(!Movie) DO ADD '- %enr'
IF F(!1) DO ADD 'v%ver'
DO ADD ' (%res'
IF R(DVD),R(Blu-ray) DO ADD ' %src'
DO ADD ' %vid'
IF Z(10) DO ADD ' %bitbit'
DO ADD ') '
DO ADD '[%CRC]'

DO REPLACE ' ' '_' // replace spaces with underscores
DO REPLACE 'H264/AVC' 'H264'
DO REPLACE '0x0' ''
DO REPLACE '__' '_'
DO REPLACE '__' '_'

DO REPLACE '<' '('
DO REPLACE '>' ')'
DO REPLACE ':' '-'
DO REPLACE '"' '`'
DO REPLACE '/' '_'
DO REPLACE '/' '_'
DO REPLACE '\' '_'
DO REPLACE '|' '_'
DO REPLACE '?' '_'
DO REPLACE '*' '_'
```

﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

## VERSION INFORMATION

Server Version:  3.8.0.0

Desktop Version:  3.8.0.0

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE

ATTACH YOUR LOGS HERE
[2017-08-12.txt](https://github.com/ShokoAnime/ShokoServer/files/1219869/2017-08-12.txt)

## DESCRIPTION

New files are placed in the Watched folder, server hashes, looks up against AniDB, and renames the file, but generates error in log file at the last step, which is to move file from Watched to Drop Destination.  Checked in Discord, was told to change paths from UNC format to Windows mapped drives, restarted, same result.  Both the Drop Source and Drop Destination folders are mapped folder from a Synology NAS device.

## STEPS TO REPRODUCE

Place new file in Drop Source/Watched folder.

**Comment by Cazzar** [comment]
Updated the description so it uses code blocks for readability

**Comment by maxpiva** [comment]
I'll take this, AnimeImp, is one of your destination folder or source folder a network drive/drive?

**Comment by Animeimp** [comment]
Both are network drives.  They were listed as UNC paths under 3.7, but in the Discord server I was told to move them to mapped drives under 3.8.
