### ISSUE TITLE
Duplicate entry for key UIX_CrossRef_File_Episode_Hash_EpisodeI

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#671]
Clean installation on fresh windows, 3.8.0.0. This error is after 14h of importing videos

also the `D:\Documents\GitHub\ShokoServer\Shoko.Server\Commands\Import\CommandRequest_ProcessFile.cs` is not my path its in log only, I install it from installer into `D:/Program Files/Shoko/`

```
[2017-09-07 10:31:02:829] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Error processing CommandRequest_ProcessFile: 4863 - NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Models.Server.CrossRef_File_Episode][SQL: INSERT INTO CrossRef_File_Episode (CrossRefSource, EpisodeID, EpisodeOrder, Hash, Percentage, FileName, FileSize, AnimeID) VALUES (?, ?, ?, ?, ?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Duplicate entry '919017D1A0E4261E1A7370BB0CDE5176-176270' for key 'UIX_CrossRef_File_Episode_Hash_EpisodeID'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseCachedRepository`2.Save(T obj) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Repositories\BaseCachedRepository.cs:line 173
   at Shoko.Server.Models.SVR_AniDB_File.CreateCrossEpisodes(String localFileName) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_AniDB_File.cs:line 406
   at Shoko.Server.Commands.CommandRequest_ProcessFile.ProcessFile_AniDB(SVR_VideoLocal vidLocal) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Commands\Import\CommandRequest_ProcessFile.cs:line 133
   at Shoko.Server.Commands.CommandRequest_ProcessFile.ProcessCommand() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Commands\Import\CommandRequest_ProcessFile.cs:line 77
```

**Comment by bigretromike** [comment]
Wow. That's quite a patch there. 

On September 7, 2017 8:31:04 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Closed #671 via 1adaf57963e8ee86af397c7d8491ac2c73e4e803.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/671#event-1239349605

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
I'm finding there are a lot of places where we are a little too trusting of the data we get from AniDB

**Comment by bigretromike** [comment]
We all make mistakes. Looks like they are humans also :-) 

On September 7, 2017 9:54:40 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>I'm finding there are a lot of places where we are a little too
>trusting of the data we get from AniDB
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/671#issuecomment-327910501

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
