### ISSUE TITLE
EpisodeName cannot be null Shoko.Models.Server.TvDB_Episode

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#672]
Same as #671 

```
[2017-09-07 17:31:18:849] Error|ExecutionContext.Run => ExecutionContext.RunInternal => <QueueEpisodeImageDownloadAsync>d__30.MoveNext Error in TVDBHelper.GetEpisodes: NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Models.Server.TvDB_Episode][SQL: INSERT INTO `TvDB_Episode` (AbsoluteNumber, EpImgFlag, EpisodeName, EpisodeNumber, Filename, Id, Overview, SeasonID, SeasonNumber, SeriesID, AirsAfterSeason, AirsBeforeEpisode, AirsBeforeSeason, Rating, AirDate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Column 'EpisodeName' cannot be null
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseCachedRepository`2.Save(T obj) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Repositories\BaseCachedRepository.cs:line 173
   at Shoko.Server.Providers.TvDB.TvDBApiHelper.<QueueEpisodeImageDownloadAsync>d__30.MoveNext() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBApiHelper.cs:line 809
[2017-09-07 17:31:20:130] Error|ExecutionContext.Run => ExecutionContext.RunInternal => <QueueEpisodeImageDownloadAsync>d__30.MoveNext Error in TVDBHelper.GetEpisodes: NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Models.Server.TvDB_Episode][SQL: INSERT INTO `TvDB_Episode` (AbsoluteNumber, EpImgFlag, EpisodeName, EpisodeNumber, Filename, Id, Overview, SeasonID, SeasonNumber, SeriesID, AirsAfterSeason, AirsBeforeEpisode, AirsBeforeSeason, Rating, AirDate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Column 'EpisodeName' cannot be null
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseCachedRepository`2.Save(T obj) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Repositories\BaseCachedRepository.cs:line 173
   at Shoko.Server.Providers.TvDB.TvDBApiHelper.<QueueEpisodeImageDownloadAsync>d__30.MoveNext() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBApiHelper.cs:line 809
[2017-09-07 17:31:20:911] Error|ExecutionContext.Run => ExecutionContext.RunInternal => <QueueEpisodeImageDownloadAsync>d__30.MoveNext Error in TVDBHelper.GetEpisodes: NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Models.Server.TvDB_Episode][SQL: INSERT INTO `TvDB_Episode` (AbsoluteNumber, EpImgFlag, EpisodeName, EpisodeNumber, Filename, Id, Overview, SeasonID, SeasonNumber, SeriesID, AirsAfterSeason, AirsBeforeEpisode, AirsBeforeSeason, Rating, AirDate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Column 'EpisodeName' cannot be null
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseCachedRepository`2.Save(T obj) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Repositories\BaseCachedRepository.cs:line 173
   at Shoko.Server.Providers.TvDB.TvDBApiHelper.<QueueEpisodeImageDownloadAsync>d__30.MoveNext() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBApiHelper.cs:line 809

```

**Comment by bigretromike** [comment]
@da3dsoul wasn;t you touching TvDB_Episodes recently ?

**Comment by bigretromike** [comment]
I got few of those by now, not much but few;

**Comment by bigretromike** [comment]
Good job cleaning old code.
`[System.Obsolete("This method is deprecated", false)]` should tell someone something xD

**Comment by hidden4003** [comment]
Yea I marked old methods obsolete when I did TvDB new api.
