### ISSUE TITLE
cloudfilesystem resolve() is mis-used

### ISSUE THREAD

**Issue by bond4u** [ShokoAnime/ShokoServer#685]
I was cleaning up collection and got "unable to delete file" message when deleting an episode.
server log:
```
[2017-09-24 00:40:03:828] Info|RuntimeMethodHandle.InvokeMethod => ShokoServiceImplementation.DeleteVideoLocalPlaceAndFile => SVR_VideoLocal_Place.RemoveAndDeleteFileWithMessage Deleting video local place record and file: P:\_ani\2016\01\Boku dake ga Inai Machi\[Kirion] Boku dake ga Inai Machi (Erased) - 05 (BD 720p x264 AAC).mp4
[2017-09-24 00:40:03:880] Error|RuntimeMethodHandle.InvokeMethod => ShokoServiceImplementation.DeleteVideoLocalPlaceAndFile => SVR_VideoLocal_Place.RemoveAndDeleteFileWithMessage Unable to delete file 'P:\_ani\2016\01\Boku dake ga Inai Machi\[Kirion] Boku dake ga Inai Machi (Erased) - 05 (BD 720p x264 AAC).mp4'
```
I expected Resolve() to fail, because I deleted the file manually in File Explorer, but instead Resolve() succeeded and  Delete() failed.
Obviously, Resolve() is returning cached entry and not checking actual filesystem.

I added following line to SVR_Videlocal_Place
`467: logger.Info("file '"+file.FullName+"' attr '"+file.Attributes+"'");`
and now I'm getting this:
```
[2017-09-26 09:34:27:732] Info|RuntimeMethodHandle.InvokeMethod => ShokoServiceImplementation.DeleteVideoLocalPlaceAndFile => SVR_VideoLocal_Place.RemoveAndDeleteFileWithMessage Deleting video local place record and file: P:\_ani\2014\Garo Honoo no Kokuin\[AnimeRG] Garo The Animation- 8 [1280x720] [Multi Sub] [Pseudo-Bitch].mkv
[2017-09-26 09:34:27:785] Error|RuntimeMethodHandle.InvokeMethod => ShokoServiceImplementation.DeleteVideoLocalPlaceAndFile => SVR_VideoLocal_Place.RemoveAndDeleteFileWithMessage System.IO.FileNotFoundException: The system cannot find the file specified.

   at Pri.LongPath.Common.GetAttributes(String path) in C:\Users\bond\Projects\VS\LongPath\Pri.LongPath\Common.cs:line 43
   at Pri.LongPath.FileSystemInfo.get_Attributes() in C:\Users\bond\Projects\VS\LongPath\Pri.LongPath\FileSystemInfo.cs:line 50
   at NutzCode.CloudFileSystem.Plugins.LocalFileSystem.LocalFile.get_Attributes() in C:\Users\bond\Projects\VS\ShokoServer\CloudFileSystem\NutzCode.CloudFileSystem.Plugins.LocalFileSystem\LocalFile.cs:line 33
   at Shoko.Server.Models.SVR_VideoLocal_Place.RemoveAndDeleteFileWithMessage() in C:\Users\bond\Projects\VS\ShokoServer\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 467
```

Quite often I've seen this in log:
```
[2017-09-26 06:15:35:079] Info|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo duplicate entry, fullpath: NutzCode.CloudFileSystem.FileSystemResult`1[NutzCode.CloudFileSystem.IObject]: True: G:\_torrentz\_removed\_2017\07\[Beatrice-Raws] Kimi no Na wa [BDRip 1280x720 x264 FLAC]\[Beatrice-Raws] Kimi no Na wa. (2016) [720p] [9AD926AE].mkv
[2017-09-26 06:15:35:079] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Found Duplicate File
[2017-09-26 06:15:35:079] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo ---------------------------------------------
[2017-09-26 06:15:35:079] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo New File: G:\_torrentz\_removed\_2017\07\[Beatrice-Raws] Kimi no Na wa [BDRip 1280x720 x264 FLAC]\[Beatrice-Raws] Kimi no Na wa. (2016) [720p] [9AD926AE].mkv
[2017-09-26 06:15:35:079] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Existing File: G:\_torrentz\_removed\_2017\07\[Beatrice-Raws] Kimi no Na wa [BDRip 1280x720 x264 FLAC]\[Beatrice-Raws] Kimi no Na wa. (2016) [720p] [9AD926AE].mkv
[2017-09-26 06:15:35:079] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo ---------------------------------------------
```
And when I check, "existing file" doesn't actually exist.
I'd suggest to access .Attributes before actually deleting anything based Resolve() return value.

**Comment by da3dsoul** [comment]
Yeah, I'm familiar with it, but I don't know how to fix it. @maxpiva can you disable the filesystem cache for local filesystems, please?

**Comment by bond4u** [comment]
I was wondering, OS already does caching, why the extra caching?

**Comment by da3dsoul** [comment]
The caching is for cloud, where iterating the tree may be not be fast enough.

**Comment by da3dsoul** [comment]
FIXED!
