### ISSUE TITLE
Database encoding problem ( utf8mb4_unicode_ci is not default encoding for tables for mysql )

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#718]
While importing collection I got one of this:
`[2018-03-18 12:02:18:915] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_GetAnimeHTTP.ProcessCommand Error processing CommandRequest_GetAnimeHTTP: 8895 - NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Models.Server.AniDB_Anime_Title][SQL: INSERT INTO AniDB_Anime_Title (AnimeID, Language, Title, TitleType) VALUES (?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Incorrect string value: '\xF0\x9D\x84\x87' for column 'Title' at row `1``

**Comment by Cazzar** [comment]
What do you get from

```sql

**Comment by bigretromike** [comment]
Title collation: utf8_general_ci

**Comment by Cazzar** [comment]
Do you know what title it's supposed to be, since, '\xF0\x9D\x84\x87' returns an invalid string in the most cases that I can see.

**Comment by bigretromike** [comment]
Sorry I have no idea because Im importing new collection and this is while Im lazy because of auto-ban from to many imports....
I was hoping that `CommandRequest_GetAnimeHTTP: 8895` is telling the id of anime.

**Comment by Cazzar** [comment]
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=8895 ?

y'know logs would be helpful....

**Comment by bigretromike** [comment]
``
[2018-03-18 12:02:14:126] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_GetAnimeHTTP.ProcessCommand Processing CommandRequest_GetAnimeHTTP: 8895
[2018-03-18 12:02:18:915] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_GetAnimeHTTP.ProcessCommand Error processing CommandRequest_GetAnimeHTTP: 8895 - NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Models.Server.AniDB_Anime_Title][SQL: INSERT INTO AniDB_Anime_Title (AnimeID, Language, Title, TitleType) VALUES (?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Incorrect string value: '\xF0\x9D\x84\x87' for column 'Title' at row 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseCachedRepository`2.Save(IReadOnlyCollection`1 objs) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Repositories\BaseCachedRepository.cs:line 275
   at Shoko.Server.Models.SVR_AniDB_Anime.CreateTitles(List`1 titles) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_AniDB_Anime.cs:line 1169
   at Shoko.Server.Models.SVR_AniDB_Anime.PopulateAndSaveFromHTTP(ISession session, Raw_AniDB_Anime animeInfo, List`1 eps, List`1 titles, List`1 cats, List`1 tags, List`1 chars, List`1 resources, List`1 rels, List`1 sims, List`1 recs, Boolean downloadRelations) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_AniDB_Anime.cs:line 1037
   at Shoko.Server.AniDBHelper.SaveResultsForAnimeXML(ISession session, Int32 animeID, Boolean downloadRelations, AniDBHTTPCommand_GetFullAnime getAnimeCmd) in D:\Documents\GitHub\ShokoServer\Shoko.Server\AniDBHelper.cs:line 996
   at Shoko.Server.AniDBHelper.GetAnimeInfoHTTP(ISession session, Int32 animeID, Boolean forceRefresh, Boolean downloadRelations) in D:\Documents\GitHub\ShokoServer\Shoko.Server\AniDBHelper.cs:line 987
   at Shoko.Server.AniDBHelper.GetAnimeInfoHTTP(Int32 animeID, Boolean forceRefresh, Boolean downloadRelations) in D:\Documents\GitHub\ShokoServer\Shoko.Server\AniDBHelper.cs:line 932
   at Shoko.Server.Commands.CommandRequest_GetAnimeHTTP.ProcessCommand() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Commands\AniDB\CommandRequest_GetAnimeHTTP.cs:line 42

``

**Comment by Cazzar** [comment]
https://gist.github.com in future FYI

or attach it as a file.

**Comment by bigretromike** [comment]
this is problem with 3 vs 4 bytes 8utf.
even when database is created with utf8mb4_unicode_ci titles is only set to utf8 so it throw error;
this is error on creating database thing;

**Comment by bigretromike** [comment]
@Cazzar there is nothing more there.. just few thounsends scans etc.. also even without logs it was easy to pin point. No need to throw few megs out there; no need to profiling me ;-)

**Comment by bigretromike** [comment]
`
ALTER TABLE `anidb_anime_title` CHANGE COLUMN `Title` `Title` VARCHAR(500) NOT NULL COLLATE 'utf8mb4_unicode_ci' AFTER `Language`;
`

**Comment by hidden4003** [comment]
It IS default encoding if shoko creates DB, problem here being that you provided it bad database.
https://github.com/ShokoAnime/ShokoServer/blob/784dd4c087af3e800bee275cffd36c8e3f0c3968/Shoko.Server/Databases/MySQL.cs#L860

**Comment by bigretromike** [comment]
The it looks like i used already created database;
Thanks for code-snipe; 
Looks like I need to import once more;

**Comment by bigretromike** [comment]
Sorry, but it used default that is set for MySQL ? or something;
because utf8_general_ci is still used; and im 100% right now that Shoko created this database;

**Comment by bigretromike** [comment]
https://github.com/ShokoAnime/ShokoServer/blob/784dd4c087af3e800bee275cffd36c8e3f0c3968/Shoko.Server/Databases/MySQL.cs#L73

**Comment by bigretromike** [comment]
@hidden4003

**Comment by hidden4003** [comment]
No, that is a bug made by someone who did the queries:
https://github.com/ShokoAnime/ShokoServer/blob/784dd4c087af3e800bee275cffd36c8e3f0c3968/Shoko.Server/Databases/MySQL.cs#L73

**Comment by bigretromike** [comment]
So it looks like we should probably change each utf8 to utf8mb4_unicode_ci
fix the creation script
and made patch for every other that used the script

**Comment by hidden4003** [comment]
@Cazzar is working on a patch, we can't really change existing script, with EF refactor we will start clean anyways.

**Comment by Cazzar** [comment]
Latest daily when patched built.

**Comment by bigretromike** [comment]
@Cazzar thank you kind sir;

**Comment by Cazzar** [comment]
```sql
SELECT `TABLE_SCHEMA`, `TABLE_NAME`, `COLUMN_NAME`, `DATA_TYPE`, `CHARACTER_MAXIMUM_LENGTH` FROM information_schema.COLUMNS WHERE table_schema = '{db}' AND collation_name != 'utf8mb4_unicode_ci'
```

For those wanting to know what specific columns might still be affected (should return an empty set on latest daily).

**Comment by bigretromike** [comment]
fix + fix for fix work fine; 
now db have proper encoding;
