### ISSUE TITLE
 Index was out of range while add file to MyList

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#719]
While importing fresh collection with latest daily build this is what I got in logs;
There is no issue in current stable build;

```
[2018-03-18 16:26:48:695] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Adding file to list: [Exiled-Destiny]_Fighting_Spirit_Ep66_(C0DD05A3).mkv - Not Watched
[2018-03-18 16:26:48:711] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Error processing CommandRequest_AddFileToMyList: C2A587227501B860639A77E6D418FEC9 - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Shoko.Server.Commands.CommandRequest_AddFileToMyList.ProcessCommand() in C:\projects\jmmserver\Shoko.Server\Commands\AniDB\CommandRequest_AddFileToMyList.cs:line 131
[2018-03-18 16:26:48:726] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Processing CommandRequest_AddFileToMyList: [Exiled-Destiny]_Fighting_Spirit_Ep03v2_(E77A747F).mkv - 309262F4D9F148448456D101136CCADB
[2018-03-18 16:26:51:363] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Adding file to list: [Exiled-Destiny]_Fighting_Spirit_Ep03v2_(E77A747F).mkv - Not Watched
[2018-03-18 16:26:51:363] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Error processing CommandRequest_AddFileToMyList: 309262F4D9F148448456D101136CCADB - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Shoko.Server.Commands.CommandRequest_AddFileToMyList.ProcessCommand() in C:\projects\jmmserver\Shoko.Server\Commands\AniDB\CommandRequest_AddFileToMyList.cs:line 131
```

**Comment by da3dsoul** [comment]
Thanks I'll check it
