### ISSUE TITLE
TvDbSharper.Infrastructure.ApiClient Exception Throw()

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#725]
Daily build.
While importing this came up in logs

```
[2018-03-30 13:38:51:737] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_GetReleaseGroupStatus.ProcessCommand Processing CommandRequest_GetReleaseGroupStatus: 8076
[2018-03-30 13:38:54:747] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_TvDBSearchAnime.ProcessCommand Processing CommandRequest_TvDBSearchAnime: 8076
[2018-03-30 13:39:12:001] Error|ExecutionContext.Run => ExecutionContext.RunInternal => <GetSeriesInfoOnlineAsync>d__6.MoveNext Error in TvDBApiHelper.GetSeriesInfoOnline: System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.<GetResponseAsync>d__12.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Infrastructure\ApiClient.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TvDbSharper.Infrastructure.ApiClient.<SendRequestAsync>d__9.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Infrastructure\ApiClient.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TvDbSharper.Clients.SeriesClient.<GetAsync>d__13.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Clients\SeriesClient.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Shoko.Server.Providers.TvDB.TvDBApiHelper.<GetSeriesInfoOnlineAsync>d__6.MoveNext() in C:\projects\jmmserver\Shoko.Server\Providers\TvDB\TvDBApiHelper.cs:line 73
[2018-03-30 13:39:12:032] Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_AddFileToMyList.ProcessCommand Processing CommandRequest_AddFileToMyList: [Kuromii] Houkago no Pleiades ONA  - 04 [BD 1080p 10bit FLAC][BAFBC0AD].mkv - F388DB9C83033E031E5E9ABFD1BFC1DD
```

Looking at path it shows me this is something that maxpiva did, but it looks like something broke it or something ;-)

**Comment by da3dsoul** [comment]
We wrapped our own version because we are too impatient to wait for PRs. At this point we should see if there's been any updates, and if not PR a fix and/or notify the dev

**Comment by bigretromike** [comment]
oh, sound great. I just writing those issue as I look from time to time while importing collection to new machine. And from what I see if you are in good mood I can redownload dailys few minute after the initial issue. 
Thank you senpai

**Comment by purposelycryptic** [comment]
I realize this is an older issue, but, as it is still open, I figured this might be somehow related? Having issues with MyList/Vote sync, seemingly due to MyList.XML being empty - well, except for this:

     <error code="310">illegal input or access denied</error>

which certainly seems very different, but my log shows what seems to be an attempt to access that same individual's (I'm guessing dev's?) local folder that doesn't exist on my machine.

I'm guessing the core issue is unrelated (and if I can't figure it out I'll create a new thread or something), but it did seem on some level related, so I thought it might be worth adding mention of it here - anyways, here is the log snippet I was referring to:


> 2018-07-23 22:18:16:405 Warn BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_SyncMyList.ProcessCommand AniDB did not return a successful code: NoSuchAnime at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) at Nancy.Rest.Module.Filters.Serializers.Json.JsonFilteredSerializer.Serialize[TModel](String contentType, TModel model, Stream outputStream) in  _**C:\Users\mpiva**_\Documents\GIT\Nancy.Rest\Nancy.Rest.Module\Filters\Serializers\Json\JsonFilteredSerializer.cs:line 72 at Nancy.Gzip.GzipCompression.<>c__DisplayClass4_0.<CompressResponse>b__0(Stream responseStream) at Nancy.Hosting.Self.NancyHost.OutputWithContentLength(Response nancyResponse, HttpListenerResponse response) at Nancy.Hosting.Self.NancyHost.ConvertNancyResponseToResponse(Response nancyResponse, HttpListenerResponse response) at Nancy.Hosting.Self.NancyHost.Process(HttpListenerContext ctx)
> 
> 2018-07-23 22:18:16:405 Error CommandRequest_SyncMyList.ProcessCommand => AniDBHTTPCommand_GetMyList.Process => AniDBHTTPHelper.ProcessMyList AniDB Sync_MyList - MyList xml is empty or invalid
> 
> 2018-07-23 22:18:15:941 Info BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_SyncMyList.ProcessCommand Processing CommandRequest_SyncMyList
> 
> 2018-07-23 22:13:16:244 Warn BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_SyncMyList.ProcessCommand AniDB did not return a successful code: NoSuchAnime
> 
> 2018-07-23 22:13:16:244 Error CommandRequest_SyncMyList.ProcessCommand => AniDBHTTPCommand_GetMyList.Process => AniDBHTTPHelper.ProcessMyList AniDB Sync_MyList - MyList xml is empty or invalid
> 
> 2018-07-23 22:13:15:805 Info BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_SyncMyList.ProcessCommand Processing CommandRequest_SyncMyList
> 
> 2018-07-23 22:08:17:053 Warn BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_SyncMyList.ProcessCommand AniDB did not return a successful code: NoSuchAnime
> 
> 2018-07-23 22:08:17:053 Error CommandRequest_SyncMyList.ProcessCommand => AniDBHTTPCommand_GetMyList.Process => AniDBHTTPHelper.ProcessMyList AniDB Sync_MyList - MyList xml is empty or invalid
> 
> 2018-07-23 22:03:16:817 Warn BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_SyncMyList.ProcessCommand AniDB did not return a successful code: NoSuchAnime

**Comment by da3dsoul** [comment]
That is in fact unrelated.

**Comment by da3dsoul** [comment]
Put it in a separate issue. Call it something like error in Sync MyList

**Comment by bigretromike** [comment]
@da3dsoul as someone poke  this issue, did original PR got merge or someone did the wrapper ?

**Comment by da3dsoul** [comment]
It got merged, but nothing has changed, so we haven't bothered updating

**Comment by ElementalCrisis** [comment]
Hasn't been reported again since this issue, so seems its fixed.
