### ISSUE TITLE
Shoko Server crashes while running the migration 78.11 - [MigrateTvDBLinks_v2_to_V3]

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoServer#736]
## VERSION INFORMATION

Latest source code as of yesterday

## DESCRIPTION

Shoko Server crashes while running the migration
Applying Schema Patches...78.11 - [MigrateTvDBLinks_v2_to_V3]

I have also tried running it in debug and get the following error

```
System.StackOverflowException
  HResult=0x800703E9
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

## LOG FILE

```
[2018-06-07 04:43:42:471] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Shoko Server Version: v3.8.3.19912
[2018-06-07 04:43:42:481] Warn|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Error in log (database version lookup: Object reference not set to an instance of an object.
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Operating System: Windows 8 / 2012 Server 64-bit
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MediaInfo DLL 0.7.97.0 (C:\[ JMM ]\Shoko Server\x64\MediaInfo.dll)
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Hasher DLL found at C:\[ JMM ]\Shoko Server\x64\hasher.dll
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog ----------------- SERVER SETTINGS ----------------------
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog DatabaseType: SQLServer
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MSSQL DatabaseServer: localhost
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MSSQL DatabaseName: JMMServer5
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MSSQL DatabaseUsername: ***HIDDEN***
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MSSQL DatabasePassword: ***HIDDEN***
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog SQLITE DatabaseFile: C:\Projects\JMMServer.db3
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MySQL_Hostname: localhost
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MySQL_SchemaName: 
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MySQL_Username: NOT SET
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MySQL_Password: NOT SET
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_Username: ***HIDDEN***
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_Password: ***HIDDEN***
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_ServerAddress: api.anidb.info
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_ServerPort: 9000
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_ClientPort: 4556
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_AVDumpKey: ***HIDDEN***
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_AVDumpClientPort: 4557
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_DownloadRelatedAnime: True
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_DownloadSimilarAnime: False
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_DownloadReviews: False
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_DownloadReleaseGroups: False
[2018-06-07 04:43:42:481] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MyList_AddFiles: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MyList_StorageState: HDD
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadUnwatched: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MyList_ReadWatched: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MyList_SetWatched: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MyList_SetUnwatched: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MyList_UpdateFrequency: Never
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_Calendar_UpdateFrequency: Daily
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_Anime_UpdateFrequency: HoursTwelve
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AniDB_MaxRelationDepth: 3
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_Address: omm.hobbydb.net.leaf.arvixe.com
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_Anonymous: False
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Get: False
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_XRefFileEpisode_Send: False
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_TvDB_Get: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_TvDB_Send: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_MAL_Get: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog WebCache_MAL_Send: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog TvDB_AutoFanart: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog TvDB_AutoFanartAmount: 70
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog TvDB_AutoWideBanners: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog TvDB_AutoPosters: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog TvDB_UpdateFrequency: HoursSix
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog TvDB_Language: en
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MovieDB_AutoFanart: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MovieDB_AutoFanartAmount: 10
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog MovieDB_AutoPosters: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog VideoExtensions: MKV,AVI,MP4,MOV,OGM,WMV,MPG
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog DefaultSeriesLanguage: Romaji
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog DefaultEpisodeLanguage: Romaji
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog RunImportOnStart: False
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Hash_CRC32: False
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Hash_MD5: False
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Hash_SHA1: False
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Import_UseExistingFileWatchedStatus: True
[2018-06-07 04:43:42:493] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Trakt_IsEnabled: True
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Trakt_AuthToken: NOT SET
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Trakt_RefreshToken: NOT SET
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Trakt_UpdateFrequency: HoursTwelve
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Trakt_SyncFrequency: Never
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AutoGroupSeries: True
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog AutoGroupSeriesRelationExclusions: same setting|character
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog FileQualityFilterEnabled: False
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog FileQualityFilterPreferences: {"Types":["SOURCE","RESOLUTION","AUDIOSTREAMCOUNT","SUBSTREAMCOUNT","SUBGROUP","CHAPTER","VIDEOCODEC","AUDIOCODEC","VERSION"],"PreferredAudioCodecs":["flac","dolby digital plus","dolby truehd","dts","he-aac","aac","ac3","mp3 cbr","mp3 vbr","vorbis (ogg vorbis)","wma (also divx audio)","realaudio g2/8 (cook)","alac","msaudio","opus","mp2","pcm","unknown","none"],"PreferredResolutions":["2160p","1440p","1080p","720p","480p"],"PreferredSources":["bd","dvd","hdtv","tv","www","unknown"],"PreferredSubGroups":["fffpeeps","doki","commie","horriblesubs"],"PreferredVideoCodecs":["hevc","h264/avc","divx5/6","mpeg-4 asp","mpeg-2","mpeg-1","ms mp4x","divx4","divx3","vc-1","xvid","realvideo 9/10","other (divx)","other (mpeg-4 sp)","other (realvideo)","vp8","vp6","other (vpx)","other (wmv3/wmv/9)","unknown","none"],"Prefer8BitVideo":false,"AllowDeletionOfImportedFiles":false,"RequiredTypes":["SOURCE","CHAPTER","VERSION"],"RequiredAudioCodecs":{"Item1":["flac","dolby digital plus","dolby truehd","dts","aac"],"Item2":"IN"},"RequiredAudioStreamCount":{"Item1":1,"Item2":"GREATER_EQ"},"RequiredResolutions":{"Item1":["1080p"],"Item2":"GREATER_EQ"},"RequiredSources":{"Item1":["bd","dvd"],"Item2":"IN"},"RequiredSubGroups":{"Item1":["horriblesubs"],"Item2":"NOTIN"},"RequiredSubStreamCount":{"Item1":1,"Item2":"GREATER_EQ"},"RequiredVideoCodecs":{"Item1":["hevc","h264/avc"],"Item2":"IN"},"Require10BitVideo":true,"MaxNumberOfFilesToKeep":1}
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog LanguagePreference: x-jat,en
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog LanguageUseSynonyms: True
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog EpisodeTitleSource: AniDB
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog SeriesDescriptionSource: AniDB
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog SeriesNameSource: AniDB
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog BaseImagesPath: 
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog BaseImagesPathIsDefault: True
[2018-06-07 04:43:42:508] Info|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog -------------------------------------------------------
[2018-06-07 04:43:42:572] Info|MainWindow..ctor => ShokoServer.StartUpServer => ShokoServer.SetupNetHosts Initializing Web Hosts...
[2018-06-07 04:43:48:235] Info|RuntimeType.CreateInstanceSlow => RuntimeTypeHandle.CreateInstance => MainWindow..ctor Already been set up... Initializing DB...
[2018-06-07 04:43:48:235] Info|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => ShokoServer.AniDBDispose Disposing...
[2018-06-07 04:43:48:235] Info|ShokoServer.WorkerSetupDB_DoWork => ShokoServer.AniDBDispose => AniDBHelper.Dispose ANIDBLIB DISPOSING...
[2018-06-07 04:43:48:335] Info|UIElement.RaiseEventImpl => EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded Clearing Cache...
[2018-06-07 04:43:48:356] Info|MainWindow.MainWindow_Loaded => Utils.ClearAutoUpdateCache => Utils.ExecuteCommandSync 
[2018-06-07 04:43:48:356] Info|EventRoute.InvokeHandlersImpl => MainWindow.MainWindow_Loaded => ShokoServer.CheckForUpdates Checking for updates...
[2018-06-07 04:43:49:242] Info|ShokoServer.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort -------- Local IP Addresses --------
[2018-06-07 04:43:49:242] Info|ShokoServer.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort -------- End Local IP Addresses --------
[2018-06-07 04:43:49:242] Info|ShokoServer.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToLocalPort BindToLocalPort: Bound to local address: 0.0.0.0:4556 - Port: 4556 (InterNetwork)
[2018-06-07 04:43:49:242] Info|ShokoServer.SetupAniDBProcessor => AniDBHelper.Init => AniDBHelper.BindToRemotePort BindToRemotePort: Bound to remote address: 94.130.237.200 : 9000
[2018-06-07 04:43:49:242] Info|ShokoServer.WorkerSetupDB_DoWork => ShokoServer.SetupAniDBProcessor => AniDBHelper.Init starting logout timer...
[2018-06-07 04:43:49:242] Info|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => CommandProcessorGeneral.Stop CommandProcessorGeneral has been stopped, 0 commands left.
[2018-06-07 04:43:50:252] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork Setting up database...
[2018-06-07 04:43:50:268] Info|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB Starting Server: Initializing Session Factory...
[2018-06-07 04:43:51:329] Info|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB Starting Server: New Version detected. Database Backup in progress...
[2018-06-07 04:43:57:470] Info|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB Starting Server: Shoko.Server.Databases.SQLServer - CreateAndUpdateSchema()
[2018-06-07 04:43:57:470] Info|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB Starting Server: RepoFactory.Init()
[2018-06-07 04:44:12:065] Info|ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB => BaseDatabase`1.ExecuteDatabaseFixes Starting Server: Database - Applying Schema Patches...78.11 - [MigrateTvDBLinks_v2_to_V3]
```

## EVENT VIEWER

```
Faulting application name: ShokoServer.exe, version: 3.8.3.19912, time stamp: 0x5b1732f0
Faulting module name: clr.dll, version: 4.7.3101.0, time stamp: 0x5aba99c6
Exception code: 0xc00000fd
Fault offset: 0x0000000000003047
Faulting process id: 0xd8d8
Faulting application start time: 0x01d3fdd70c13d539
Faulting application path: C:\[ JMM ]\Shoko Server\ShokoServer.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: ab316037-6532-4947-b1c1-b6bec13c45de
Faulting package full name: 
Faulting package-relative application ID: 


Fault bucket 1975040311050004535, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 1576077903336646285

Problem signature:
P1: ShokoServer.exe
P2: 3.8.3.19912
P3: 5b1732f0
P4: clr.dll
P5: 4.7.3101.0
P6: 5aba99c6
P7: c00000fd
P8: 0000000000003047
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1D4F.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER22CE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER22DF.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER22DD.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER22EE.tmp.txt
\\?\C:\Users\wernd\AppData\Local\Temp\WER2FB1.tmp.appcompat.txt
\\?\C:\Users\wernd\AppData\Local\Temp\WER3010.tmp.WERDataCollectionStatus.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ShokoServer.exe_de36812878a1dcf556d364cb9ab95e040db45_b8434561_cab_fd02b484

Analysis symbol: 
Rechecking for solution: 0
Report Id: ab316037-6532-4947-b1c1-b6bec13c45de
Report Status: 268435464
Hashed bucket: 9d8f26088387ff79cb68c0b2dd366837
Cab Guid: db243200-5c3d-4ceb-95df-5a80aeb9268d
```

**Comment by da3dsoul** [comment]
StackOverflow huh....

**Comment by da3dsoul** [comment]
I'll look at it later

**Comment by bigretromike** [comment]
@jmediamanager wb. How big is your collection ?

**Comment by jmediamanager** [comment]
Anime	2,097
Episodes	32,287
Files	        34,534
Size	        10.97 TB

**Comment by da3dsoul** [comment]
I assume that you can consistently reproduce it. Can you debug it to tell me where it crashes?

**Comment by da3dsoul** [comment]
That's a large method

**Comment by da3dsoul** [comment]
Also update first, as I might have fixed it

**Comment by jmediamanager** [comment]
I get this error now

```
2018-06-12 10:59:36:134] Info|ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB => BaseDatabase`1.ExecuteDatabaseFixes Starting Server: Database - Applying Schema Patches...78.11 - [MigrateTvDBLinks_v2_to_V3]
[2018-06-12 10:59:42:086] Error|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB DATABASE ERROR: 78.11 [MigrateTvDBLinks_v2_to_V3] | System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.TvDBLinkingHelper.GetSpecialsOverridesFromLegacy(List`1 links) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBLinkingHelper.cs:line 800
   at Shoko.Server.TvDBLinkingHelper.GetSpecialsOverridesFromLegacy(List`1 links) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBLinkingHelper.cs:line 740
   at Shoko.Server.Databases.DatabaseFixes.MigrateTvDBLinks_v2_to_V3() in C:\Projects\GitHub\ShokoServer\Shoko.Server\Databases\DatabaseFixes.cs:line 199
   at Shoko.Server.Databases.BaseDatabase`1.ExecuteDatabaseFixes() in C:\Projects\GitHub\ShokoServer\Shoko.Server\Databases\BaseDatabase.cs:line 148
[2018-06-12 10:59:42:129] Error|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB Could not init database: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.get_CriticalHandle()
   at System.Windows.MessageBox.Show(Window owner, String messageBoxText, String caption, MessageBoxButton button, MessageBoxImage icon)
   at Shoko.UI.MainWindow.<SubscribeEvents>b__8_2(Object sender, ErrorEventArgs args) in C:\Projects\GitHub\ShokoServer\Shoko.UI\MainWindow.xaml.cs:line 194
   at Shoko.Server.Utils.ShowErrorMessage(String title, String msg) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Utils.cs:line 438
   at Shoko.Server.Databases.DatabaseFactory.InitDB(String& errorMessage) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Databases\DatabaseFactory.cs:line 114

```

**Comment by da3dsoul** [comment]
Okay I just pushed a fix to that. Try the latest after it builds

**Comment by jmediamanager** [comment]
Looks like an issue with the recursive call

The anime id below is 10091 (it fails on this one every time)

```
public List<AniDB_Anime_Relation> GetByAnimeID(ISessionWrapper session, int id)
        {
            var cats = session
                .CreateCriteria(typeof(AniDB_Anime_Relation))
                .Add(Restrictions.Eq("AnimeID", id))
                .List<AniDB_Anime_Relation>();

            return new List<AniDB_Anime_Relation>(cats);
        }
```

![image](https://user-images.githubusercontent.com/6645153/41266427-24f09018-6e3a-11e8-8711-ab7ae212612a.png)

**Comment by da3dsoul** [comment]
Thank you. I shall investigate that

**Comment by da3dsoul** [comment]
Okay. Should be fixed now

**Comment by jmediamanager** [comment]
Got past that bit, but now getting the following error
```

[2018-06-12 16:15:47:480] Info|ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB => BaseDatabase`1.ExecuteDatabaseFixes Starting Server: Database - Applying Schema Patches...78.11 - [MigrateTvDBLinks_v2_to_V3]
[2018-06-12 16:24:36:840] Info|ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB => BaseDatabase`1.ExecuteDatabaseFixes Starting Server: Database - Applying Schema Patches...79.1 - [FixAniDB_EpisodesWithMissingTitles]
[2018-06-12 16:27:42:391] Info|ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB => BaseDatabase`1.PopulateInitialData Starting Server: Database - Populating Data (Users)...
[2018-06-12 16:27:42:397] Info|ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB => BaseDatabase`1.PopulateInitialData Starting Server: Database - Populating Data (Group Filters)...
[2018-06-12 16:27:42:397] Info|ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB => BaseDatabase`1.PopulateInitialData Starting Server: Database - Populating Data (Locked Group Filters)...
[2018-06-12 16:28:29:914] Error|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB Could not init database: System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.Repositories.Cached.CrossRef_AniDB_TvDBRepository.<>c.<GetV2LinksFromAnime>b__12_3(ValueTuple`2 a) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Repositories\Cached\CrossRef_AniDB_TvDBRepository.cs:line 103
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Shoko.Server.Repositories.Cached.CrossRef_AniDB_TvDBRepository.GetV2LinksFromAnime(Int32 animeID) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Repositories\Cached\CrossRef_AniDB_TvDBRepository.cs:line 100
   at Shoko.Server.Models.SVR_AnimeSeries.UpdateContract(Boolean onlystats) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Models\SVR_AnimeSeries.cs:line 690
   at Shoko.Server.Repositories.Cached.GroupFilterRepository.CreateOrVerifyDirectoryFilters(Boolean frominit, HashSet`1 tags, HashSet`1 airdate, SortedSet`1 seasons) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Repositories\Cached\GroupFilterRepository.cs:line 406
   at Shoko.Server.Repositories.Cached.GroupFilterRepository.CreateOrVerifyLockedFilters() in C:\Projects\GitHub\ShokoServer\Shoko.Server\Repositories\Cached\GroupFilterRepository.cs:line 259
   at Shoko.Server.Databases.BaseDatabase`1.CreateOrVerifyLockedFilters() in C:\Projects\GitHub\ShokoServer\Shoko.Server\Databases\BaseDatabase.cs:line 239
   at Shoko.Server.Databases.BaseDatabase`1.PopulateInitialData() in C:\Projects\GitHub\ShokoServer\Shoko.Server\Databases\BaseDatabase.cs:line 224
   at Shoko.Server.Databases.DatabaseFactory.InitDB(String& errorMessage) in C:\Projects\GitHub\ShokoServer\Shoko.Server\Databases\DatabaseFactory.cs:line 108

```

**Comment by da3dsoul** [comment]
The fuck did you do to your DB? I'll add more sanitizing where it shouldn't be needed but apparently is

**Comment by jmediamanager** [comment]
Actually I think we can close this.
I restored back to an older version of the database and it seems to be working now.

**Comment by bigretromike** [comment]
This is how it ends after fucking up db with those patches. The more you run those the better it gets. Been there hehehe. Someone need to break one or two dbs so other don't have to. 

On June 12, 2018 8:33:06 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>The fuck did you do to your DB? I'll add more sanitizing where it
>shouldn't be needed but apparently is
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/736#issuecomment-396480669

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Shame I just pushed more sanitizing

**Comment by da3dsoul** [comment]
Okay

**Comment by bigretromike** [comment]
Better now than later. I prefer wait 10 more minutes than restore db in future 😃

On June 12, 2018 8:45:03 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Shame I just pushed more sanitizing
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ShokoAnime/ShokoServer/issues/736#issuecomment-396483033

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
