### ISSUE TITLE
Fails to move/rename files, CancellationTokenSource has been disposed

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoServer#775]
Having major issues getting the server to move and rename the files to the destination folder. 
Manually issuing the file rename in the File Renaming tab in Shoko Desktop ends in an error: `ERROR: The CancellationTokenSource has been disposed.`

This issue happens when both the `Move if Needed` option is ticked on or off, has no say.

Shoko Desktop v3.9.4.0
Shoko Server Windows v3.9.4.16188

**Comment by ElementalCrisis** [comment]
Anything else in the logs?

**Comment by CuddleBear92** [comment]
Two different ones, One Piece is being imported for the first time, Casshern Sins is being manually renamed in the desktop client (since it didnt work the first time)

> [2019-02-20 03:06:47:396] Error|RuntimeMethodInfo.UnsafeInvokeInternal => RuntimeMethodHandle.InvokeMethod => ShokoServiceImplementation.RenameAndMoveFile System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Shoko.Server.ShokoServer.StopWatchingFiles() in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\ShokoServer.cs:line 1326
   at Shoko.Server.ShokoServer.StartWatchingFiles(Boolean log) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\ShokoServer.cs:line 1278
   at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 199
   at Shoko.Server.ShokoServiceImplementation.RenameAndMoveFile(Int32 videoLocalID, String scriptName, Boolean move) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\API\v1\Implementations\ShokoServiceImplementation\ShokoServiceImplementation_Utilities.cs:line 519
[2019-02-20 03:06:48:298] Info|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Renaming file FAILED! From (M:\Anime\One Piece\[AnimeRG] One Piece - 801 [720p] [Multi-Sub] [HEVC] [x265] [pseudo].mkv) to (M:\Anime\One Piece\One Piece - 801 (1280x720 unknown) [AnimeRG] (17C6FAE6).mkv) - The CancellationTokenSource has been disposed.
[2019-02-20 03:06:48:298] Error|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at LeanWork.IO.FileSystem.BufferingFileSystemWatcher.Dispose(Boolean disposing) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\Utilities\LeanWork\IO\FileSystem\BufferingFileSystemWatcher.cs:line 405
   at System.ComponentModel.Component.Dispose()
   at Shoko.Server.ShokoServer.StopWatchingFiles() in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\ShokoServer.cs:line 1326
   at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 131
[2019-02-20 03:06:48:977] Info|RuntimeMethodHandle.InvokeMethod => ShokoServiceImplementation.RenameAndMoveFile => SVR_VideoLocal_Place.RenameFile Renaming file FAILED! From (M:\Anime\Casshern Sins\[Cleo]Casshern_Sins_-_20_(Dual Audio_10bit_BD720p_x265).mkv) to (M:\Anime\Casshern Sins\Casshern Sins - 20 (1280x720 Blu-ray HEVC 10bit) [Cleo] (F884DE4C).mkv) - The CancellationTokenSource has been disposed.

Note, this also stops the client from moving the file to its destination folder.
Series folder creation is still happening on new imports, seeing only a few files getting moved and renamed out of a whole season for some series.

**Comment by CuddleBear92** [comment]
Also got this one for the first time.

> [2019-02-20 03:06:47:396] Error|RuntimeMethodInfo.UnsafeInvokeInternal => RuntimeMethodHandle.InvokeMethod => ShokoServiceImplementation.RenameAndMoveFile System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Shoko.Server.ShokoServer.StopWatchingFiles() in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\ShokoServer.cs:line 1326
   at Shoko.Server.ShokoServer.StartWatchingFiles(Boolean log) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\ShokoServer.cs:line 1278
   at Shoko.Server.Models.SVR_VideoLocal_Place.RenameFile(Boolean preview, String scriptName) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\Models\SVR_VideoLocal_Place.cs:line 199
   at Shoko.Server.ShokoServiceImplementation.RenameAndMoveFile(Int32 videoLocalID, String scriptName, Boolean move) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\API\v1\Implementations\ShokoServiceImplementation\ShokoServiceImplementation_Utilities.cs:line 519
[2019-02-20 03:06:48:298] Info|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Renaming file FAILED! From (M:\Anime\One Piece\[AnimeRG] One Piece - 801 [720p] [Multi-Sub] [HEVC] [x265] [pseudo].mkv) to (M:\Anime\One Piece\One Piece - 801 (1280x720 unknown) [AnimeRG] (17C6FAE6).mkv) - The CancellationTokenSource has been disposed.

**Comment by da3dsoul** [comment]
Should be fixed
