### ISSUE TITLE
Column 'File_AudioCodec' in AniDb_File is to small

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoServer#777]
```
2019-03-19 07:26:40:252] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Error processing CommandRequest_ProcessFile: 25011 - NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Server.Models.SVR_AniDB_File][SQL: INSERT INTO AniDB_File (Anime_GroupName, Anime_GroupNameShort, AnimeID, CRC, DateTimeUpdated, Episode_Rating, Episode_Votes, File_AudioCodec, File_Description, File_FileExtension, File_LengthSeconds, File_ReleaseDate, File_Source, File_VideoCodec, File_VideoResolution, FileID, FileName, FileSize, FileVersion, IsCensored, IsDeprecated, IsChaptered, InternalVersion, GroupID, Hash, IsWatched, MD5, SHA1, WatchedDate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] ---> MySql.Data.MySqlClient.MySqlException: Data too long for column 'File_AudioCodec' at row 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractSelectingDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseCachedRepository`2.Save(T obj) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\Repositories\BaseCachedRepository.cs:line 245
   at Shoko.Server.Commands.CommandRequest_ProcessFile.ProcessFile_AniDB(SVR_VideoLocal vidLocal) in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\Commands\Import\CommandRequest_ProcessFile.cs:line 147
   at Shoko.Server.Commands.CommandRequest_ProcessFile.ProcessCommand() in C:\Users\da3ds\Documents\GitHub\ShokoServer3.9.3\Shoko.Server\Commands\Import\CommandRequest_ProcessFile.cs:line 75
```

On importing file, those get ignored because one file throw error.

This is the value that want to be saved:
`Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus'Dolby Digital Plus`

**Comment by bigretromike** [comment]
Patched for MySQL, looks like no other database was affected by this.
