### ISSUE TITLE
Unable to link series to TvDB

### ISSUE THREAD

**Issue by ayrtsia** [ShokoAnime/ShokoServer#779]
﻿Suddenly whenever I add a new series I can't link it to the TvDB. Clicking on the search button does nothing and when trying to add using the series number brings the error "The series data is being downloaded, try again when the queue is cleared." Even though the queue is empty. Server and desktop version 3.9.4. 

Server error log: 

`[2019-04-07 17:43:49:082] Error|ExecutionContext.Run => ExecutionContext.RunInternal => <CheckAuthorizationAsync>d__4.MoveNext Error in TvDBAuth: System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.<GetResponseAsync>d__12.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Infrastructure\ApiClient.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TvDbSharper.Infrastructure.ApiClient.<SendRequestAsync>d__9.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Infrastructure\ApiClient.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TvDbSharper.Clients.AuthenticationClient.<AuthenticateAsync>d__13.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Clients\AuthenticationClient.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Shoko.Server.Providers.TvDB.TvDBApiHelper.<CheckAuthorizationAsync>d__4.MoveNext() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBApiHelper.cs:line 47
[2019-04-07 17:43:49:082] Error|ExecutionContext.Run => ExecutionContext.RunInternal => <GetSeriesInfoOnlineAsync>d__6.MoveNext Error in TvDBApiHelper.GetSeriesInfoOnline: System.NullReferenceException: Object reference not set to an instance of an object.
   at TvDbSharper.Infrastructure.ApiClient.<GetResponseAsync>d__12.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Infrastructure\ApiClient.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TvDbSharper.Infrastructure.ApiClient.<SendRequestAsync>d__9.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Infrastructure\ApiClient.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TvDbSharper.Clients.AuthenticationClient.<AuthenticateAsync>d__13.MoveNext() in C:\Users\mpiva\Downloads\TvDbSharper-master\TvDbSharper-master\src\TvDbSharper\Clients\AuthenticationClient.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Shoko.Server.Providers.TvDB.TvDBApiHelper.<CheckAuthorizationAsync>d__4.MoveNext() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBApiHelper.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Shoko.Server.Providers.TvDB.TvDBApiHelper.<GetSeriesInfoOnlineAsync>d__6.MoveNext() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Providers\TvDB\TvDBApiHelper.cs:line 70
`

**Comment by ayrtsia** [comment]
I managed to fix this, it turned out to be my router blocking api.thetvdb.com. I whitelisted it and everything was working again.
