### ISSUE TITLE
I don't have a database, fresh install "Failed to start review database"

### ISSUE THREAD

**Issue by cartals** [ShokoAnime/ShokoServer#817]
I didn't do anything just logged on my anidb account and tested. Sucessfully but it said after than failed to start review database. Using latest stable.
[2020-04-26.log](https://github.com/ShokoAnime/ShokoServer/files/4536446/2020-04-26.log)

**Comment by da3dsoul** [comment]
Try daily

**Comment by cartals** [comment]
It doesn't even open.

**Comment by ElementalCrisis** [comment]
```
[2020-04-26 23:48:31:622] Error|BackgroundWorker.OnDoWork => ShokoServer.WorkerSetupDB_DoWork => DatabaseFactory.InitDB DATABASE ERROR: 4.1 ALTER TABLE AnimeGroup ADD DefaultAnimeSeriesID int NULL | System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
duplicate column name: DefaultAnimeSeriesID
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at Shoko.Server.Databases.SQLite.Execute(SQLiteConnection connection, String command) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Databases\SQLite.cs:line 759
   at Shoko.Server.Databases.SQLite.ExecuteCommand(SQLiteConnection connection, String command) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Databases\SQLite.cs:line 746
```

@da3dsoul seems there was an error altering the SQLite DB.

**Comment by da3dsoul** [comment]
What he said

**Comment by da3dsoul** [comment]
That could possibly happen if the server is killed or something else interferes at just the wrong time

**Comment by cartals** [comment]
Yes wrong time.

**Comment by da3dsoul** [comment]
It works then? Cool
