### ISSUE TITLE
After upgrade to 3.9.7 errors on most video files for Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered:

### ISSUE THREAD

**Issue by runecalico** [ShokoAnime/ShokoServer#829]
﻿## PLEASE READ BEFORE POSTING YOUR ISSUE

Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on Discord.

https://discord.gg/vpeHDsg

===== Guidelines ====

- Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed.
- Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before.
- If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop **LOG FILE**. 
- If requesting a new feature, please explain in detail the feature itself and the benefits of it being added.
- If requesting cosmetic changes, please explain in detail why they should be made. 
- The template below **MUST BE USED** when submitting an issue, no exceptions.

## VERSION INFORMATION

Server Version: 
3.9.7.28738

Desktop Version: 

If you've compiled your own version, please use the last commit you compiled.

## LOG FILE
After upgrading from 3.9.6 to 3.9.7, the initial startup is very very slowly progressing as it looks like it's trying to do this step on every video file, but it's only produced 2 errors in 30 minutes (actually only 2 log entries), with mediaInfoWrapper chewing up 100% of a single CPU

[2020-06-17 18:25:33:329] Error|VideoLocalRepository.UpdateMediaContracts => SVR_VideoLocal_Place.RefreshMediaInfo => MediaInfo.GetMediaInfoFromWrapper MediaInfo threw an error on [HorribleSubs] Vinland Saga - 16 [720p].mkv: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: 7. Path ' P a r t s [0]. S i z e ', line 1, position 116.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.Skip()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Shoko.Server.Utilities.MediaInfoLib.MediaInfo.GetMediaInfoFromWrapper(String filename) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Utilities\MediaInfoLib\MediaInfo.cs:line 50
[2020-06-17 18:25:33:438] Error|VideoLocalRepository.Save => VideoLocalRepository.UpdateMediaContracts => SVR_VideoLocal_Place.RefreshMediaInfo File [HorribleSubs] Vinland Saga - 16 [720p].mkv failed to read MediaInfo

If I use MediaGui 20.03, this is the "json" view on this specific file ..
{
"media": {
"@ref": "[HorribleSubs] Vinland Saga - 16 [720p].mkv",
"track": [
{
"@type": "General",
"FileExtension": "mkv",
"FileSize": "275113584",
"StreamSize": "275113584",
"File_Created_Date": "UTC 2020-06-17 23:39:17.327",
"File_Created_Date_Local": "2020-06-17 18:39:17.327",
"File_Modified_Date": "UTC 2019-10-28 03:00:23.000",
"File_Modified_Date_Local": "2019-10-27 22:00:23.000"
}
]
}
}

## DESCRIPTION

I was running on 3.9.6, imported a bunch of video's and upgraded to 3.9.7.

## STEPS TO REPRODUCE
Upgrade to 3.9.7 after running 3.9.6 with stuff.

Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it.

**Comment by da3dsoul** [comment]
Yep. It'll be fixed in the next release. If it's preventing startup, then rename MediaInfoWrapper.exe temporarily.

**Comment by runecalico** [comment]
Thanks, that does the trick. Will that cause other problems by renaming it?

**Comment by da3dsoul** [comment]
It'll stop MediaInfo from being generated, so a lot of things will have missing info. It'll repopulate in the next version, though
