### ISSUE TITLE
File imports do not move from drop source to drop destination with Default renamer script empty

### ISSUE THREAD

**Issue by fieldhouse** [ShokoAnime/ShokoServer#853]
## VERSION INFORMATION

Server Version: 4.0.1.0

Desktop Version: 4.0.0.0

## LOG FILE

=======
moved gohs 8 out of watched folders && ran remove missing files
=======
```
[2020-10-13 15:54:14:601] Info|BackgroundWorker.WorkerThreadStart => ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles Remove Missing Files: Start
[2020-10-13 15:54:16:341] Info|BackgroundWorker.WorkerThreadStart => ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles Removing Missing File: 22435
[2020-10-13 15:54:16:341] Info|ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles => SVR_VideoLocal_Place.RemoveRecordWithOpenTransaction Removing VideoLocal_Place record for: /animeroot/Anime/Seeding/God of High School/[HorribleSubs] The God of High School - 08 [1080p].mkv
[2020-10-13 15:54:18:996] Info|BackgroundWorker.WorkerThreadStart => ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles Removing Missing File: 22650
[2020-10-13 15:54:18:997] Info|ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles => SVR_VideoLocal_Place.RemoveRecordWithOpenTransaction Removing VideoLocal_Place record for: /animeroot/Anime/import/[HorribleSubs] Tower of God - 13 [720p].mkv
[2020-10-13 15:54:19:301] Info|BackgroundWorker.WorkerThreadStart => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_DeleteFileFromMyList.ProcessCommand Processing CommandRequest_DeleteFileFromMyList: MyListID: 301161444
[2020-10-13 15:54:24:450] Info|BackgroundWorker.WorkerThreadStart => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_DeleteFileFromMyList.ProcessCommand Marking file as unknown: MyListID: 301161444
[2020-10-13 15:54:52:228] Info|BackgroundWorker.WorkerThreadStart => ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles Remove Missing Files: Finished
[2020-10-13 15:54:53:865] Info|BackgroundWorker.WorkerThreadStart => CommandProcessorGeneral.WorkerCommands_DoWork => SVR_AnimeSeries.UpdateStats Starting Updating STATS for SERIES Kami no Tou - Watched Stats: True, Missing Episodes: True, Update Group Stats: True
[2020-10-13 15:54:55:357] Info|CommandProcessorGeneral.WorkerCommands_DoWork => SVR_AnimeSeries.UpdateStats => SVR_AnimeGroup.UpdateStatsFromTopLevel Starting Updating STATS for GROUP Tower of God from Top Level (recursively) - Watched Stats: True, Missing Episodes: True, Groups Only: True
[2020-10-13 15:54:55:357] Info|SVR_AnimeSeries.UpdateStats => SVR_AnimeGroup.UpdateStatsFromTopLevel => SVR_AnimeGroup.UpdateStats Starting Updating STATS for GROUP Tower of God - Watched Stats: True, Missing Episodes: True
```

========
script is empty, run script is unchecked
move file to watched drop source
========
```
[2020-10-13 16:04:08:401] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => ShokoServer.WorkerFileEvents_DoWork New file detected: /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv: Created
[2020-10-13 16:04:08:401] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => ShokoServer.WorkerFileEvents_DoWork Found file /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv
[2020-10-13 16:04:14:260] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Found Duplicate File
[2020-10-13 16:04:14:261] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo ---------------------------------------------
[2020-10-13 16:04:14:263] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo New File: /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv
[2020-10-13 16:04:14:263] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Existing File: /animeroot/Anime/Seeding/God of High School/[HorribleSubs]_The_God_of_High_School_-_08_(1920x1080_unknown)_[43A9D6AD].mkv
[2020-10-13 16:04:14:264] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo ---------------------------------------------
[2020-10-13 16:04:18:304] Info|CommandRequest_ProcessFile.ProcessFile_AniDB => EnumerableExtensions.ForEach => SVR_AnimeSeries.UpdateStats Starting Updating STATS for SERIES The God of High School - Watched Stats: True, Missing Episodes: True, Update Group Stats: True
[2020-10-13 16:04:36:013] Info|EnumerableExtensions.ForEach => SVR_AnimeSeries.UpdateStats => SVR_AnimeGroup.UpdateStatsFromTopLevel Starting Updating STATS for GROUP The God of High School from Top Level (recursively) - Watched Stats: True, Missing Episodes: True, Groups Only: True
[2020-10-13 16:04:36:016] Info|SVR_AnimeSeries.UpdateStats => SVR_AnimeGroup.UpdateStatsFromTopLevel => SVR_AnimeGroup.UpdateStats Starting Updating STATS for GROUP The God of High School - Watched Stats: True, Missing Episodes: True
[2020-10-13 16:05:04:503] Info|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Renaming file SKIPPED! no change From (/animeroot/Anime/Seeding/God of High School/[HorribleSubs]_The_God_of_High_School_-_08_(1920x1080_unknown)_[43A9D6AD].mkv) to (/animeroot/Anime/Seeding/God of High School/[HorribleSubs]_The_God_of_High_School_-_08_(1920x1080_unknown)_[43A9D6AD].mkv)
[2020-10-13 16:05:04:513] Error|List`1.ForEach => SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.MoveFileIfRequired Could not MOVE file: /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv -- System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.RenameFileHelper.GetDestination(SVR_VideoLocal_Place place) in /usr/src/app/source/Shoko.Server/Renamer/RenameFileHelper.cs:line 63
   at Shoko.Server.Models.SVR_VideoLocal_Place.MoveFileIfRequired() in /usr/src/app/source/Shoko.Server/Models/SVR_VideoLocal_Place.cs:line 863
[2020-10-13 16:05:04:647] Info|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Renaming file SKIPPED! no change From (/animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv) to (/animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv)
```
=========
remove file from folder / run remove missing from library
=========
```
[2020-10-13 16:06:35:479] Info|BackgroundWorker.WorkerThreadStart => ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles Remove Missing Files: Start
[2020-10-13 16:06:37:321] Info|BackgroundWorker.WorkerThreadStart => ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles Removing Missing File: 22435
[2020-10-13 16:06:37:321] Info|ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles => SVR_VideoLocal_Place.RemoveRecordWithOpenTransaction Removing VideoLocal_Place record for: /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv
[2020-10-13 16:07:19:750] Info|BackgroundWorker.WorkerThreadStart => ShokoServer.WorkerRemoveMissing_DoWork => Importer.RemoveRecordsWithoutPhysicalFiles Remove Missing Files: Finished
```
=========
script is empty, run script is checked
(check box, then hit save) Script drop down in Desktop now says "Defalt(Run On Import)"  (instead of just "Default")
expected behavior: file should move from drop source to `<drop dest>\<anime title>\<original filename>`
=========
```
[2020-10-13 16:09:07:511] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => ShokoServer.WorkerFileEvents_DoWork New file detected: /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv: Created
[2020-10-13 16:09:07:513] Info|BackgroundWorker.WorkerThreadStart => BackgroundWorker.OnDoWork => ShokoServer.WorkerFileEvents_DoWork Found file /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv
[2020-10-13 16:09:21:104] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Found Duplicate File
[2020-10-13 16:09:21:105] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo ---------------------------------------------
[2020-10-13 16:09:21:105] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo New File: /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv
[2020-10-13 16:09:21:105] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo Existing File: /animeroot/Anime/Seeding/God of High School/[HorribleSubs]_The_God_of_High_School_-_08_(1920x1080_unknown)_[43A9D6AD].mkv
[2020-10-13 16:09:21:106] Warn|CommandProcessorHasher.WorkerCommands_DoWork => CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo ---------------------------------------------
[2020-10-13 16:10:57:784] Info|CommandRequest_ProcessFile.ProcessFile_AniDB => EnumerableExtensions.ForEach => SVR_AnimeSeries.UpdateStats Starting Updating STATS for SERIES The God of High School - Watched Stats: True, Missing Episodes: True, Update Group Stats: True
[2020-10-13 16:10:58:762] Info|EnumerableExtensions.ForEach => SVR_AnimeSeries.UpdateStats => SVR_AnimeGroup.UpdateStatsFromTopLevel Starting Updating STATS for GROUP The God of High School from Top Level (recursively) - Watched Stats: True, Missing Episodes: True, Groups Only: True
[2020-10-13 16:10:58:763] Info|SVR_AnimeSeries.UpdateStats => SVR_AnimeGroup.UpdateStatsFromTopLevel => SVR_AnimeGroup.UpdateStats Starting Updating STATS for GROUP The God of High School - Watched Stats: True, Missing Episodes: True
[2020-10-13 16:11:05:240] Error|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Error: The renamer returned an error on file: God of High School/[HorribleSubs]_The_God_of_High_School_-_08_(1920x1080_unknown)_[43A9D6AD].mkv
            *Error: the new filename is empty (script error)
[2020-10-13 16:11:05:252] Info|List`1.ForEach => SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.MoveFileIfRequired Moving file from /animeroot/Anime/import/[HorribleSubs] The God of High School - 08 [1080p].mkv to /animeroot/Anime/Seeding/God of High School/[HorribleSubs] The God of High School - 08 [1080p].mkv
[2020-10-13 16:11:05:741] Error|SVR_VideoLocal_Place.RenameAndMoveAsRequired => SVR_VideoLocal_Place.RenameIfRequired => SVR_VideoLocal_Place.RenameFile Error: The renamer returned an error on file: God of High School/[HorribleSubs] The God of High School - 08 [1080p].mkv
            *Error: the new filename is empty (script error)
```

## DESCRIPTION
if “run script” is unchecked files are not moved.
if “run script” is checked then files are moved.  But they are moved to the wrong folder.
expected behavior: file should move from drop source to `<drop dest>\<anime title>\<original filename>`
in the past this was the case regardless of whether the renamer script is enabled - just the nature of having the drop source and drop destination set.

This may be related to #849 

## STEPS TO REPRODUCE
assuming empty default renamer script:
move file out of watched folder, run remove missing files from library.
move file into watched drop source.
to enable, check box to enable script then hit save.  Script drop down in Desktop now says "Defalt(Run On Import)"  instead of just "Default"

<img width="604" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/2186295/95926422-1cc3ed80-0d71-11eb-820c-4e1ef0c83c52.png">
<img width="520" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/2186295/95926429-22213800-0d71-11eb-8b17-ad80c25506e4.png">
<img width="540" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/2186295/95926447-306f5400-0d71-11eb-8d17-81f192711a4d.png">

**Comment by Cazzar** [comment]
@fieldhouse is this issue still occurring since the latest release?

**Comment by ElementalCrisis** [comment]
Closing issue as no response from @fieldhouse.
