### ISSUE TITLE
Permanently getting banned from AniDB UDP Api

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/ShokoServer#854]
## VERSION INFORMATION

Server Version: 4.0.1

Desktop Version: 4.0.0

## LOG FILE

[2020-10-15.log](https://github.com/ShokoAnime/ShokoServer/files/5384376/2020-10-15.log)

## DESCRIPTION

Somehow, im getting banned from AnidbUDP Api constantly now. And if the ban is lifted, im getting banned again shortly after.
(Commands in queue around 80- 100)

## STEPS TO REPRODUCE

1.) Have some anidb upd command queued
2.) let server process them

**Comment by Cazzar** [comment]
Couple of questions

Do you have any other things interacting with the AniDB UDP API at the same time?
Add you possibly behind CG-NAT/LSN?

**Comment by Cazzar** [comment]
Going by the log:
`[2020-10-15 11:58:25:648] Error|<>c.<Configure>b__9_0 => AsyncMethodBuilderCore.Start => <<Configure>b__9_0>d.MoveNext System.IO.IOException: The process cannot access the file 'C:\ProgramData\ShokoServer\settings-server.json' because it is being used by another process.`
You have another version of Shoko possibly running.

**Comment by t0815** [comment]
hm, no i only run 1 instance. But, i did copy my shoko data folder from a different host system to now one. Maybe some rights problem.

**Comment by t0815** [comment]
Dang! Write protection on shoko-data folder....

Never the less, the error:
`[2020-10-15 15:57:55:468] Error|<>c.<Configure>b__9_0 => AsyncMethodBuilderCore.Start => <<Configure>b__9_0>d.MoveNext System.IO.IOException: The process cannot access the file 'C:\ProgramData\ShokoServer\settings-server.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Shoko.Server.Settings.ServerSettings.SaveSettings() in E:\Documents\GitHub\ShokoServer\Shoko.Server\Settings\ServerSettings.cs:line 401
   at Shoko.Server.API.v3.Controllers.SettingsController.SetSettings(JsonPatchDocument`1 settings, Boolean skipValidation) in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\v3\Controllers\SettingsController.cs:line 53
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Shoko.Server.API.Startup.<>c.<<Configure>b__9_0>d.MoveNext() in E:\Documents\GitHub\ShokoServer\Shoko.Server\API\Startup.cs:line 184
`
Is still occuring. Maybe its a threading issue? One thread has file already locked? But at least the banned isssue seems to be solved. Strange tho.

**Comment by Cazzar** [comment]
@t0815 sorry about the slow response, things get busy sometimes.

Ultimately, it looks like one of a few possibilities
Since that error is ultimately saying that the file is already open by some other process therefore you could be 
- running 2 instances of shook at once (shouldn't typically happen, though it can in some edge cases)
- More likely have the settings file open in something like notepad/some other editor causing an exclusive file lock.
