### ISSUE TITLE
JsonSerializationException in LoadLegacySettings 

### ISSUE THREAD

**Issue by Scrxtchy** [ShokoAnime/ShokoServer#879]
## VERSION INFORMATION

Server Version: 4.1.0 Stable

Desktop Version: N/A

## LOG FILE
<details>
  <summary>Log File</summary>

```
[2021-03-15 21:28:31:637] Error|ServerSettings.LoadSettings => ServerSettings.LoadLegacySettings => ServerSettings_Legacy.LoadSettingsFromFile Newtonsoft.Json.JsonSerializationException: Error converting value "{"Types":["SOURCE","RESOLUTION","AUDIOSTREAMCOUNT","SUBSTREAMCOUNT","SUBGROUP","CHAPTER","VIDEOCODEC","AUDIOCODEC","VERSION"],"PreferredAudioCodecs":["flac","dolby digital plus","dolby truehd","dts","he-aac","aac","ac3","mp3 cbr","mp3 vbr","vorbis (ogg vorbis)","wma (also divx audio)","realaudio g2/8 (cook)","alac","msaudio","opus","mp2","pcm","unknown","none"],"PreferredResolutions":["2160p","1440p","1080p","720p","480p"],"PreferredSources":["bd","dvd","hdtv","tv","www","unknown"],"PreferredSubGroups":["fffpeeps","doki","commie","horriblesubs"],"PreferredVideoCodecs":["hevc","h264/avc","divx5/6","mpeg-4 asp","mpeg-2","mpeg-1","ms mp4x","divx4","divx3","vc-1","xvid","realvideo 9/10","other (divx)","other (mpeg-4 sp)","other (realvideo)","vp8","vp6","other (vpx)","other (wmv3/wmv/9)","unknown","none"],"Prefer8BitVideo":false,"AllowDeletionOfImportedFiles":false,"RequiredTypes":["SOURCE","CHAPTER","VERSION"],"RequiredAudioCodecs":{"Item1":["flac","dolby digital plus","dolby truehd","dts","aac"],"Item2":"IN"},"RequiredAudioStreamCount":{"Item1":1,"Item2":"GREATER_EQ"},"RequiredResolutions":{"Item1":["1080p"],"Item2":"GREATER_EQ"},"RequiredSources":{"Item1":["bd","dvd"],"Item2":"IN"},"RequiredSubGroups":{"Item1":["horriblesubs"],"Item2":"NOTIN"},"RequiredSubStreamCount":{"Item1":1,"Item2":"GREATER_EQ"},"RequiredVideoCodecs":{"Item1":["hevc","h264/avc"],"Item2":"IN"},"Require10BitVideo":true,"MaxNumberOfFilesToKeep":1}" to type 'Shoko.Models.FileQualityPreferences'. Path 'FileQualityFilterPreferences', line 111, position 1707.
 ---> System.ArgumentException: Could not cast or convert from System.String to Shoko.Models.FileQualityPreferences.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Shoko.Server.Settings.Migration.ServerSettings_Legacy.LoadSettingsFromFile() in E:\Documents\GitHub\ShokoServer\Shoko.Server\Settings\Migration\ServerSettings_Legacy.cs:line 72

[2021-03-15 21:38:03:611] Error|ServerSettings.LoadSettings => ServerSettings.LoadLegacySettings => ServerSettings_Legacy.LoadSettingsFromFile Newtonsoft.Json.JsonSerializationException: Error converting value "6" to type 'System.Int32[]'. Path 'Plex_Libraries', line 115, position 23.
 ---> System.ArgumentException: Could not cast or convert from System.String to System.Int32[].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Shoko.Server.Settings.Migration.ServerSettings_Legacy.LoadSettingsFromFile() in E:\Documents\GitHub\ShokoServer\Shoko.Server\Settings\Migration\ServerSettings_Legacy.cs:line 72
```

</details>

## DESCRIPTION

Application crashes silently on startup due to the json file being present being *way too old* and incompatible with the legacy migrator.

## STEPS TO REPRODUCE

trigger a legacy setting migration with the following settings in place
```json
{
"FileQualityFilterPreferences": "{\"Types\":[\"SOURCE\",\"RESOLUTION\",\"AUDIOSTREAMCOUNT\",\"SUBSTREAMCOUNT\",\"SUBGROUP\",\"CHAPTER\",\"VIDEOCODEC\",\"AUDIOCODEC\",\"VERSION\"],\"PreferredAudioCodecs\":[\"flac\",\"dolby digital plus\",\"dolby truehd\",\"dts\",\"he-aac\",\"aac\",\"ac3\",\"mp3 cbr\",\"mp3 vbr\",\"vorbis (ogg vorbis)\",\"wma (also divx audio)\",\"realaudio g2/8 (cook)\",\"alac\",\"msaudio\",\"opus\",\"mp2\",\"pcm\",\"unknown\",\"none\"],\"PreferredResolutions\":[\"2160p\",\"1440p\",\"1080p\",\"720p\",\"480p\"],\"PreferredSources\":[\"bd\",\"dvd\",\"hdtv\",\"tv\",\"www\",\"unknown\"],\"PreferredSubGroups\":[\"fffpeeps\",\"doki\",\"commie\",\"horriblesubs\"],\"PreferredVideoCodecs\":[\"hevc\",\"h264/avc\",\"divx5/6\",\"mpeg-4 asp\",\"mpeg-2\",\"mpeg-1\",\"ms mp4x\",\"divx4\",\"divx3\",\"vc-1\",\"xvid\",\"realvideo 9/10\",\"other (divx)\",\"other (mpeg-4 sp)\",\"other (realvideo)\",\"vp8\",\"vp6\",\"other (vpx)\",\"other (wmv3/wmv/9)\",\"unknown\",\"none\"],\"Prefer8BitVideo\":false,\"AllowDeletionOfImportedFiles\":false,\"RequiredTypes\":[\"SOURCE\",\"CHAPTER\",\"VERSION\"],\"RequiredAudioCodecs\":{\"Item1\":[\"flac\",\"dolby digital plus\",\"dolby truehd\",\"dts\",\"aac\"],\"Item2\":\"IN\"},\"RequiredAudioStreamCount\":{\"Item1\":1,\"Item2\":\"GREATER_EQ\"},\"RequiredResolutions\":{\"Item1\":[\"1080p\"],\"Item2\":\"GREATER_EQ\"},\"RequiredSources\":{\"Item1\":[\"bd\",\"dvd\"],\"Item2\":\"IN\"},\"RequiredSubGroups\":{\"Item1\":[\"horriblesubs\"],\"Item2\":\"NOTIN\"},\"RequiredSubStreamCount\":{\"Item1\":1,\"Item2\":\"GREATER_EQ\"},\"RequiredVideoCodecs\":{\"Item1\":[\"hevc\",\"h264/avc\"],\"Item2\":\"IN\"},\"Require10BitVideo\":true,\"MaxNumberOfFilesToKeep\":1}",
"Plex_Libraries": "6",
}
```

I was able to bodge a fix by outright removing the filequality filter settings as I would rather spend the time to rebuild than anything else. The plex number was instead replaced to be an single item array of the int rather than as a string.

Likely came from 3.9.4 or earlier (from commit history), there are not much remnants of what version this came from as the logs folder was cleared on installation of stable

**Comment by Scrxtchy** [comment]
Minor note, if CloudWatcherTime does not exist in the JSON, it looked to have defaulted to an un-permitted value of 0, as the default is 3. This breaks the webui

**Comment by Cazzar** [comment]
Given the fact that this only occurs with migrations of much older versions, adding the extra overhead to try and migrate this across wouldn't be a great this, it would be best to simply manually fix in the process.
